function [bestPar, bestPenalty] = tuneParam( ...
    initParams, ...
    simufunc, ...
    penaltyfunc, ...
    newParamGenerator, ...
    targetDataSets, ...
    count, ...
    fields, ...
    stepSize)

bestPar = initParams;
bestPenalty = inf;
acceptedCount = 0;
fprintf("========== Tuning Start ==========\n");

for loopNum = 1:count
    candidatePar = newParamGenerator( ...
        bestPar, ...
        fields, ...
        stepSize, ...
        loopNum);
    % Run simulation
    simres = simufunc(candidatePar);
    penalty = 0;
    for i = 1:numel(targetDataSets)
            penalty = penalty + ...
                penaltyfunc(targetDataSets{i}, simres );
    end
    penalty = penalty / numel(targetDataSets);
    fprintf( ...
        "Loop %4d | Penalty = %.8f | Step = %.6f\n", ...
        loopNum, ...
        penalty, ...
        stepSize);
    % Accept candidate if improved
    if penalty < bestPenalty
        bestPenalty = penalty;
        bestPar = candidatePar;
        acceptedCount = acceptedCount + 1;
        fprintf( ...
            "  -> Accepted New Best %f\n", penalty);

        % adaptive step increase
        stepSize = stepSize;
    else
        % adaptive step decrease
        stepSize = stepSize;

    end

    % Clamp step size， 
    stepSize = max(stepSize, 1e-6);
    stepSize = min(stepSize, 10);

end

fprintf("========== Tuning Finished ==========\n");

fprintf("Best Penalty = %.8f\n", ...
    bestPenalty);

end