clear;
clc;
close all;

addpath("param/", "model/");

%% Four-gain Monte Carlo study for the equilibrium-curve controller
%
% Controller:
%
%   s     = r - C_eq*tan(theta)
%   s_dot = r_dot - C_eq*sec(theta)^2*theta_dot
%
%   F = m*g*sin(theta)
%       - k1*s
%       - d1*s_dot
%       + k_theta*theta
%       + d_theta*theta_dot
%
% All four gains are sampled independently.  Because a four-dimensional
% result cannot be displayed directly in one two-dimensional heat map, the
% script creates two projections for each performance metric:
%
%   1. (k1, d1), marginalizing over k_theta and d_theta
%   2. (k_theta, d_theta), marginalizing over k1 and d1
%
% Every sample is simulated with the nonlinear model.  Only samples that
% satisfy the balance criteria contribute to the heat maps.

%% 1. System parameters

par = LatParam();

m = par.m_rod;
R = par.R;
g = par.g;
G = par.G;

C_eq = (G + m*g*R)/(m*g);

%% 2. Monte Carlo gain ranges
%
% Gain order used throughout the script:
%   [k1, d1, k_theta, d_theta]

number_of_samples = 100000;
random_seed = 1;

gain_min = [
    200, ... % k1      [N/m]
    5,   ... % d1      [N*s/m]
    0,   ... % k_theta [N/rad]
    0        % d_theta [N*s/rad]
];

gain_max = [
    1400, ... % k1      [N/m]
    100,  ... % d1      [N*s/m]
    80,   ... % k_theta [N/rad]
    30        % d_theta [N*s/rad]
];

% Current gains, shown by the black-centered white markers.
nominal_gains = [800, 40, 20, 5];

% Four-dimensional uniform sampling can miss a narrow stable neighborhood.
% Use part of the samples globally and part near the known working gains.
global_sample_fraction = 0.50;

local_half_range = [
    300, ... % k1 half-range around nominal [N/m]
    20,  ... % d1 half-range around nominal [N*s/m]
    20,  ... % k_theta half-range around nominal [N/rad]
    5       % d_theta half-range around nominal [N*s/rad]
];

rng(random_seed);

number_of_global_samples = round( ...
    global_sample_fraction*number_of_samples);

number_of_local_samples = ...
    number_of_samples - number_of_global_samples;

global_gain_samples = gain_min + ...
    rand(number_of_global_samples, 4).*(gain_max - gain_min);

local_gain_samples = nominal_gains + ...
    (2*rand(number_of_local_samples, 4) - 1).*local_half_range;

local_gain_samples = max( ...
    gain_min, ...
    min(gain_max, local_gain_samples));

gain_samples = [
    global_gain_samples;
    local_gain_samples
];

% Mix global and local samples, then force inclusion of the current gains.
gain_samples = gain_samples(randperm(number_of_samples), :);
gain_samples(1, :) = nominal_gains;

k1_samples = gain_samples(:, 1);
d1_samples = gain_samples(:, 2);
k_theta_samples = gain_samples(:, 3);
d_theta_samples = gain_samples(:, 4);

%% 3. Initial condition
%
% State order used by LatModel_SignCorrection:
%   z = [theta; theta_dot; r; r_dot]

theta0 = 0.10;  % rad
theta_dot0 = 0; % rad/s
r0 = 0;         % m
r_dot0 = 0;     % m/s

z0 = [
    theta0;
    theta_dot0;
    r0;
    r_dot0
];

%% 4. Simulation and balance settings

tspan = [0, 30];

% Reference hardware limits.  The controller is not saturated during the
% Monte Carlo study because the goal is to measure the force that each gain
% tuple actually requests.
hardware_force_limit = 27.6; % N
hardware_rod_limit = 0.10;   % m

% Terminate clearly invalid simulations early.
fall_limit = 27*pi/180;       % rad
simulation_rod_guard = 2.0;   % m
simulation_force_guard = 1e4; % N

% The selection mode controls which samples are used in the heat maps.
%
%   'completed'  - completed 30 s without a fall/rod-guard event
%   'stationary' - completed and nearly stationary on the curve
%   'origin'     - stationary and close to the upright origin
%
% Start with 'completed'.  The summary still reports all three levels, so a
% stricter mode can be selected later without changing the simulations.
balance.selection_mode = 'completed';

% Thresholds for the stricter stationary/origin classifications.
balance.tail_duration = 2.0;        % s
balance.max_theta_dot = 0.02;       % rad/s
balance.max_r_dot = 0.02;           % m/s
balance.max_surface_error = 0.005;  % m
balance.max_surface_speed = 0.02;   % m/s

balance.max_final_theta = 1.0*pi/180; % rad
balance.max_final_r = 0.01;            % m

ode_options = odeset( ...
    'RelTol', 1e-5, ...
    'AbsTol', 1e-7, ...
    'MaxStep', 0.02, ...
    'Events', @(t, z) stopEvents( ...
        t, z, fall_limit, simulation_rod_guard));

% Parallel execution is strongly recommended for 100,000 nonlinear runs.
% The script automatically falls back to a normal for-loop if the Parallel
% Computing Toolbox is unavailable.
use_parallel = true;
parallel_available = ...
    ~isempty(ver('parallel')) && ...
    license('test', 'Distrib_Computing_Toolbox');

progress_interval = 5000;
parallel_progress_batch = 100;

%% 5. Diagnose the current nominal controller before the full Monte Carlo run

nominal_result = simulateGainTuple( ...
    par, C_eq, z0, tspan, ode_options, ...
    nominal_gains(1), nominal_gains(2), ...
    nominal_gains(3), nominal_gains(4), ...
    simulation_force_guard, balance);

printNominalDiagnostics(nominal_gains, nominal_result, balance);

%% 6. Allocate Monte Carlo records

max_force_record = nan(number_of_samples, 1);
max_r_record = nan(number_of_samples, 1);
completed_idx = false(number_of_samples, 1);
event_stopped_idx = false(number_of_samples, 1);
stationary_idx = false(number_of_samples, 1);
origin_converged_idx = false(number_of_samples, 1);
simulation_failed_idx = false(number_of_samples, 1);

tail_theta_dot_record = nan(number_of_samples, 1);
tail_r_dot_record = nan(number_of_samples, 1);
tail_surface_error_record = nan(number_of_samples, 1);
tail_surface_speed_record = nan(number_of_samples, 1);
tail_theta_record = nan(number_of_samples, 1);
tail_r_record = nan(number_of_samples, 1);

fprintf('Four-gain equilibrium-curve Monte Carlo study\n');
fprintf('  Samples         = %d\n', number_of_samples);
fprintf('  Global samples  = %d\n', number_of_global_samples);
fprintf('  Local samples   = %d\n', number_of_local_samples);
fprintf('  Initial theta   = %.6f rad\n', theta0);
fprintf('  Initial r       = %.6f m\n', r0);
fprintf('  k1 range        = [%.3f, %.3f] N/m\n', ...
    gain_min(1), gain_max(1));
fprintf('  d1 range        = [%.3f, %.3f] N*s/m\n', ...
    gain_min(2), gain_max(2));
fprintf('  k_theta range   = [%.3f, %.3f] N/rad\n', ...
    gain_min(3), gain_max(3));
fprintf('  d_theta range   = [%.3f, %.3f] N*s/rad\n\n', ...
    gain_min(4), gain_max(4));

%% 7. Run 100,000 nonlinear simulations

if use_parallel && parallel_available

    fprintf('Running with parfor.\n');

    progress_queue = parallel.pool.DataQueue;
    afterEach( ...
        progress_queue, ...
        @(completed_batch) updateParallelProgress( ...
            completed_batch, number_of_samples, progress_interval));

    parfor sample_index = 1:number_of_samples

        gains = gain_samples(sample_index, :);

        result = simulateGainTuple( ...
            par, C_eq, z0, tspan, ode_options, ...
            gains(1), gains(2), gains(3), gains(4), ...
            simulation_force_guard, balance);

        max_force_record(sample_index) = result.max_force;
        max_r_record(sample_index) = result.max_r;
        completed_idx(sample_index) = result.completed;
        event_stopped_idx(sample_index) = result.event_stopped;
        stationary_idx(sample_index) = result.stationary;
        origin_converged_idx(sample_index) = result.origin_converged;
        simulation_failed_idx(sample_index) = result.failed;
        tail_theta_dot_record(sample_index) = result.tail_max_theta_dot;
        tail_r_dot_record(sample_index) = result.tail_max_r_dot;
        tail_surface_error_record(sample_index) = ...
            result.tail_max_surface_error;
        tail_surface_speed_record(sample_index) = ...
            result.tail_max_surface_speed;
        tail_theta_record(sample_index) = result.tail_max_theta;
        tail_r_record(sample_index) = result.tail_max_r;

        if mod(sample_index, parallel_progress_batch) == 0
            send(progress_queue, parallel_progress_batch);
        end
    end

else

    fprintf('Running with a serial for-loop.\n');

    for sample_index = 1:number_of_samples

        gains = gain_samples(sample_index, :);

        result = simulateGainTuple( ...
            par, C_eq, z0, tspan, ode_options, ...
            gains(1), gains(2), gains(3), gains(4), ...
            simulation_force_guard, balance);

        max_force_record(sample_index) = result.max_force;
        max_r_record(sample_index) = result.max_r;
        completed_idx(sample_index) = result.completed;
        event_stopped_idx(sample_index) = result.event_stopped;
        stationary_idx(sample_index) = result.stationary;
        origin_converged_idx(sample_index) = result.origin_converged;
        simulation_failed_idx(sample_index) = result.failed;
        tail_theta_dot_record(sample_index) = result.tail_max_theta_dot;
        tail_r_dot_record(sample_index) = result.tail_max_r_dot;
        tail_surface_error_record(sample_index) = ...
            result.tail_max_surface_error;
        tail_surface_speed_record(sample_index) = ...
            result.tail_max_surface_speed;
        tail_theta_record(sample_index) = result.tail_max_theta;
        tail_r_record(sample_index) = result.tail_max_r;

        if mod(sample_index, progress_interval) == 0 || ...
           sample_index == number_of_samples

            fprintf( ...
                'Monte Carlo progress: %d / %d\n', ...
                sample_index, number_of_samples);
        end
    end
end

%% 8. Monte Carlo summary and sample selection

switch lower(balance.selection_mode)
    case 'completed'
        balanced_idx = completed_idx;
        selection_description = ...
            'completed without a fall or rod-guard event';
    case 'stationary'
        balanced_idx = stationary_idx;
        selection_description = ...
            'stationary on the equilibrium curve';
    case 'origin'
        balanced_idx = origin_converged_idx;
        selection_description = ...
            'stationary near the upright origin';
    otherwise
        error( ...
            'MC_EquilibriumCurve:UnknownSelectionMode', ...
            'Unknown balance.selection_mode: %s', ...
            balance.selection_mode);
end

force_valid_idx = balanced_idx & ...
    max_force_record <= hardware_force_limit;

rod_valid_idx = balanced_idx & ...
    max_r_record <= hardware_rod_limit;

both_valid_idx = force_valid_idx & rod_valid_idx;

fprintf('\nMonte Carlo summary\n');
fprintf('  Total samples:        %d\n', number_of_samples);
fprintf('  Simulation failed:    %d\n', nnz(simulation_failed_idx));
fprintf('  Event stopped:        %d\n', nnz(event_stopped_idx));
fprintf('  Completed 30 s:       %d\n', nnz(completed_idx));
fprintf('  Stationary on curve:  %d\n', nnz(stationary_idx));
fprintf('  Converged to origin:  %d\n', nnz(origin_converged_idx));
fprintf('  Selected mode:        %s\n', balance.selection_mode);
fprintf('  Selected samples:     %d\n', nnz(balanced_idx));
fprintf('  Force-limit valid:    %d\n', nnz(force_valid_idx));
fprintf('  Rod-limit valid:      %d\n', nnz(rod_valid_idx));
fprintf('  Both limits valid:    %d\n', nnz(both_valid_idx));

normalized_demand = max( ...
    max_force_record/hardware_force_limit, ...
    max_r_record/hardware_rod_limit);

normalized_demand(~balanced_idx) = NaN;
finite_score_indices = find(isfinite(normalized_demand));

if ~isempty(finite_score_indices)

    [best_score, local_index] = min( ...
        normalized_demand(finite_score_indices));

    best_index = finite_score_indices(local_index);

    fprintf('\nLowest normalized hardware demand among selected samples\n');
    fprintf('  sample index   = %d\n', best_index);
    fprintf('  k1             = %.9g N/m\n', k1_samples(best_index));
    fprintf('  d1             = %.9g N*s/m\n', d1_samples(best_index));
    fprintf('  k_theta        = %.9g N/rad\n', ...
        k_theta_samples(best_index));
    fprintf('  d_theta        = %.9g N*s/rad\n', ...
        d_theta_samples(best_index));
    fprintf('  max|F|         = %.9g N\n', max_force_record(best_index));
    fprintf('  max|r|         = %.9g m\n', max_r_record(best_index));
    fprintf('  normalized max = %.9g\n', best_score);
else
    fprintf('\nNo sample satisfied selection mode: %s.\n', ...
        balance.selection_mode);
end

%% 9. Construct the four-dimensional heat-map projections
%
% Each sample already contains a time-domain maximum, max|F| or max|r|.
% Multiple selected Monte Carlo samples fall into each two-dimensional bin.
% The statistic below determines how those maxima are combined.
%
% Available choices:
%   'median'  - representative balanced sample in each bin
%   'minimum' - best balanced sample in each bin
%   'maximum' - worst balanced sample in each bin

number_of_bins = 35;
minimum_selected_samples_per_bin = 1;
heatmap_statistic = 'median';

balanced_k1 = k1_samples(balanced_idx);
balanced_d1 = d1_samples(balanced_idx);
balanced_k_theta = k_theta_samples(balanced_idx);
balanced_d_theta = d_theta_samples(balanced_idx);
balanced_max_force = max_force_record(balanced_idx);
balanced_max_r = max_r_record(balanced_idx);

[ ...
    force_k1_d1_map, ...
    k1_centers, ...
    d1_centers, ...
    count_k1_d1 ...
] = makeBinnedMap( ...
    balanced_k1, balanced_d1, balanced_max_force, ...
    gain_min(1), gain_max(1), gain_min(2), gain_max(2), ...
    number_of_bins, heatmap_statistic, ...
    minimum_selected_samples_per_bin);

[ ...
    force_ktheta_dtheta_map, ...
    k_theta_centers, ...
    d_theta_centers, ...
    count_ktheta_dtheta ...
] = makeBinnedMap( ...
    balanced_k_theta, balanced_d_theta, balanced_max_force, ...
    gain_min(3), gain_max(3), gain_min(4), gain_max(4), ...
    number_of_bins, heatmap_statistic, ...
    minimum_selected_samples_per_bin);

[ ...
    r_k1_d1_map, ...
    ~, ...
    ~, ...
    ~ ...
] = makeBinnedMap( ...
    balanced_k1, balanced_d1, balanced_max_r, ...
    gain_min(1), gain_max(1), gain_min(2), gain_max(2), ...
    number_of_bins, heatmap_statistic, ...
    minimum_selected_samples_per_bin);

[ ...
    r_ktheta_dtheta_map, ...
    ~, ...
    ~, ...
    ~ ...
] = makeBinnedMap( ...
    balanced_k_theta, balanced_d_theta, balanced_max_r, ...
    gain_min(3), gain_max(3), gain_min(4), gain_max(4), ...
    number_of_bins, heatmap_statistic, ...
    minimum_selected_samples_per_bin);

fprintf('\nHeat-map coverage\n');
fprintf('  Selection: %s\n', selection_description);
fprintf('  (k1, d1) bins with selected samples:       %d / %d\n', ...
    nnz(count_k1_d1 >= minimum_selected_samples_per_bin), ...
    numel(count_k1_d1));
fprintf('  (k_theta, d_theta) bins with selected samples: %d / %d\n', ...
    nnz(count_ktheta_dtheta >= minimum_selected_samples_per_bin), ...
    numel(count_ktheta_dtheta));

%% 10. Heat-map group 1: maximum requested force

plotHeatmapGroup( ...
    k1_centers, d1_centers, force_k1_d1_map, ...
    k_theta_centers, d_theta_centers, force_ktheta_dtheta_map, ...
    nominal_gains, hardware_force_limit, ...
    heatmap_statistic, ...
    sprintf( ...
        'Maximum requested force: %s samples', ...
        balance.selection_mode), ...
    'max |F| (N)');

%% 11. Heat-map group 2: maximum rod displacement

plotHeatmapGroup( ...
    k1_centers, d1_centers, r_k1_d1_map, ...
    k_theta_centers, d_theta_centers, r_ktheta_dtheta_map, ...
    nominal_gains, hardware_rod_limit, ...
    heatmap_statistic, ...
    sprintf( ...
        'Maximum rod displacement: %s samples', ...
        balance.selection_mode), ...
    'max |r| (m)');

%% 12. Save the expensive Monte Carlo result

save_results = true;
result_filename = 'MC_EquilibriumCurve_100k_results.mat';

if save_results
    save( ...
        result_filename, ...
        'gain_samples', ...
        'gain_min', ...
        'gain_max', ...
        'nominal_gains', ...
        'global_sample_fraction', ...
        'local_half_range', ...
        'nominal_result', ...
        'max_force_record', ...
        'max_r_record', ...
        'balanced_idx', ...
        'completed_idx', ...
        'event_stopped_idx', ...
        'stationary_idx', ...
        'origin_converged_idx', ...
        'simulation_failed_idx', ...
        'tail_theta_dot_record', ...
        'tail_r_dot_record', ...
        'tail_surface_error_record', ...
        'tail_surface_speed_record', ...
        'tail_theta_record', ...
        'tail_r_record', ...
        'force_valid_idx', ...
        'rod_valid_idx', ...
        'both_valid_idx', ...
        'theta0', ...
        'theta_dot0', ...
        'r0', ...
        'r_dot0', ...
        'tspan', ...
        'hardware_force_limit', ...
        'hardware_rod_limit', ...
        'balance', ...
        'random_seed');

    fprintf('\nSaved Monte Carlo records to %s\n', result_filename);
end

%% Local functions

function result = simulateGainTuple( ...
        par, C_eq, z0, tspan, ode_options, ...
        k1, d1, k_theta, d_theta, force_guard, balance)

    result.max_force = NaN;
    result.max_r = NaN;
    result.completed = false;
    result.event_stopped = false;
    result.stationary = false;
    result.origin_converged = false;
    result.failed = false;
    result.final_time = tspan(1);
    result.final_theta = NaN;
    result.final_r = NaN;
    result.tail_max_theta_dot = NaN;
    result.tail_max_r_dot = NaN;
    result.tail_max_surface_error = NaN;
    result.tail_max_surface_speed = NaN;
    result.tail_max_theta = NaN;
    result.tail_max_r = NaN;

    controller = @(t, z, p) equilibriumCurveController( ...
        t, z, p, C_eq, ...
        k1, d1, k_theta, d_theta, force_guard);

    model_rhs = @(t, z) LatModel_SignCorrection( ...
        t, z, par, controller);

    try
        [t, z, event_time] = ode45( ...
            model_rhs, ...
            tspan, ...
            z0, ...
            ode_options);
    catch
        result.failed = true;
        return;
    end

    if isempty(t) || isempty(z) || ...
       any(~isfinite(t(:))) || any(~isfinite(z(:)))

        result.failed = true;
        return;
    end

    result.final_time = t(end);
    result.final_theta = z(end, 1);
    result.final_r = z(end, 3);
    result.event_stopped = ~isempty(event_time);

    theta = z(:, 1);
    theta_dot = z(:, 2);
    r = z(:, 3);
    r_dot = z(:, 4);

    cos_theta = cos(theta);

    if any(~isfinite(cos_theta)) || any(abs(cos_theta) < 1e-6)
        result.failed = true;
        return;
    end

    s = r - C_eq*tan(theta);
    s_dot = r_dot - ...
        C_eq./(cos_theta.^2).*theta_dot;

    F = ...
        par.m_rod*par.g*sin(theta) ...
        - k1*s ...
        - d1*s_dot ...
        + k_theta*theta ...
        + d_theta*theta_dot;

    if any(~isfinite(F)) || any(abs(F) > force_guard)
        result.failed = true;
        return;
    end

    result.max_force = max(abs(F));
    result.max_r = max(abs(r));

    result.completed = ...
        isempty(event_time) && ...
        t(end) >= tspan(end) - 1e-10*max(1, abs(tspan(end)));

    if ~result.completed
        return;
    end

    tail_start = tspan(end) - balance.tail_duration;
    tail_indices = t >= tail_start;

    if ~any(tail_indices)
        tail_indices(end) = true;
    end

    result.tail_max_theta_dot = ...
        max(abs(theta_dot(tail_indices)));

    result.tail_max_r_dot = ...
        max(abs(r_dot(tail_indices)));

    result.tail_max_surface_error = ...
        max(abs(s(tail_indices)));

    result.tail_max_surface_speed = ...
        max(abs(s_dot(tail_indices)));

    result.tail_max_theta = ...
        max(abs(theta(tail_indices)));

    result.tail_max_r = ...
        max(abs(r(tail_indices)));

    result.stationary = ...
        result.tail_max_theta_dot <= balance.max_theta_dot && ...
        result.tail_max_r_dot <= balance.max_r_dot && ...
        result.tail_max_surface_error <= balance.max_surface_error && ...
        result.tail_max_surface_speed <= balance.max_surface_speed;

    result.origin_converged = ...
        result.stationary && ...
        result.tail_max_theta <= balance.max_final_theta && ...
        result.tail_max_r <= balance.max_final_r;
end

function printNominalDiagnostics(gains, result, balance)

    fprintf('\nNominal-gain diagnostic before Monte Carlo\n');
    fprintf('  gains [k1, d1, k_theta, d_theta]\n');
    fprintf('        = [%.6g, %.6g, %.6g, %.6g]\n', ...
        gains(1), gains(2), gains(3), gains(4));
    fprintf('  final time                 = %.6f s\n', ...
        result.final_time);
    fprintf('  simulation failed          = %d\n', result.failed);
    fprintf('  event stopped              = %d\n', result.event_stopped);
    fprintf('  completed full simulation  = %d\n', result.completed);
    fprintf('  max|F|                     = %.9g N\n', ...
        result.max_force);
    fprintf('  max|r|                     = %.9g m\n', ...
        result.max_r);
    fprintf('  final theta                = %.9g rad\n', ...
        result.final_theta);
    fprintf('  final r                    = %.9g m\n', ...
        result.final_r);
    fprintf('  tail max|theta_dot|        = %.9g  (limit %.9g)\n', ...
        result.tail_max_theta_dot, balance.max_theta_dot);
    fprintf('  tail max|r_dot|            = %.9g  (limit %.9g)\n', ...
        result.tail_max_r_dot, balance.max_r_dot);
    fprintf('  tail max|s|                = %.9g  (limit %.9g)\n', ...
        result.tail_max_surface_error, balance.max_surface_error);
    fprintf('  tail max|s_dot|            = %.9g  (limit %.9g)\n', ...
        result.tail_max_surface_speed, balance.max_surface_speed);
    fprintf('  tail max|theta|            = %.9g  (origin limit %.9g)\n', ...
        result.tail_max_theta, balance.max_final_theta);
    fprintf('  tail max|r|                = %.9g  (origin limit %.9g)\n', ...
        result.tail_max_r, balance.max_final_r);
    fprintf('  stationary on curve        = %d\n', result.stationary);
    fprintf('  converged to origin        = %d\n\n', ...
        result.origin_converged);

    if ~result.completed
        warning( ...
            'MC_EquilibriumCurve:NominalDidNotComplete', ...
            ['The current gains did not complete the full simulation. ' ...
             'Inspect the diagnostic before running 100,000 samples.']);
    end
end

function F = equilibriumCurveController( ...
        ~, z, par, C_eq, ...
        k1, d1, k_theta, d_theta, force_guard)

    theta = z(1);
    theta_dot = z(2);
    r = z(3);
    r_dot = z(4);

    cos_theta = cos(theta);

    if ~isfinite(cos_theta) || abs(cos_theta) < 1e-6
        error( ...
            'equilibriumCurveController:TanSingularity', ...
            'cos(theta) is too close to zero.');
    end

    sec2_theta = 1/(cos_theta^2);

    s = r - C_eq*tan(theta);
    s_dot = r_dot - C_eq*sec2_theta*theta_dot;

    F = ...
        par.m_rod*par.g*sin(theta) ...
        - k1*s ...
        - d1*s_dot ...
        + k_theta*theta ...
        + d_theta*theta_dot;

    if ~isfinite(F) || abs(F) > force_guard
        error( ...
            'equilibriumCurveController:ForceGuard', ...
            'Requested force is nonfinite or exceeds the simulation guard.');
    end
end

function [value, isterminal, direction] = stopEvents( ...
        ~, z, fall_limit, rod_guard)

    value = [
        fall_limit - abs(z(1));
        rod_guard - abs(z(3))
    ];

    isterminal = [1; 1];
    direction = [-1; -1];
end

function updateParallelProgress( ...
        completed_batch, number_of_samples, progress_interval)

    persistent completed_count next_report

    if isempty(completed_count)
        completed_count = 0;
        next_report = progress_interval;
    end

    completed_count = completed_count + completed_batch;

    while completed_count >= next_report
        fprintf( ...
            'Monte Carlo progress: %d / %d\n', ...
            min(next_report, number_of_samples), ...
            number_of_samples);

        next_report = next_report + progress_interval;
    end
end

function [metric_map, x_centers, y_centers, sample_count] = ...
        makeBinnedMap( ...
            x, y, metric, ...
            x_min, x_max, y_min, y_max, ...
            number_of_bins, statistic_name, minimum_sample_count)

    x_edges = linspace(x_min, x_max, number_of_bins + 1);
    y_edges = linspace(y_min, y_max, number_of_bins + 1);

    x_centers = 0.5*(x_edges(1:end-1) + x_edges(2:end));
    y_centers = 0.5*(y_edges(1:end-1) + y_edges(2:end));

    x_bin = discretize(x, x_edges);
    y_bin = discretize(y, y_edges);

    valid = ...
        isfinite(x_bin) & ...
        isfinite(y_bin) & ...
        isfinite(metric);

    x_bin = x_bin(valid);
    y_bin = y_bin(valid);
    metric = metric(valid);

    linear_bin = sub2ind( ...
        [number_of_bins, number_of_bins], ...
        y_bin, ...
        x_bin);

    switch lower(statistic_name)
        case 'median'
            statistic_function = @median;
        case 'minimum'
            statistic_function = @min;
        case 'maximum'
            statistic_function = @max;
        otherwise
            error( ...
                'makeBinnedMap:UnknownStatistic', ...
                'Unknown heat-map statistic: %s', ...
                statistic_name);
    end

    map_vector = accumarray( ...
        linear_bin, ...
        metric, ...
        [number_of_bins^2, 1], ...
        statistic_function, ...
        NaN);

    count_vector = accumarray( ...
        linear_bin, ...
        1, ...
        [number_of_bins^2, 1], ...
        @sum, ...
        0);

    metric_map = reshape( ...
        map_vector, ...
        number_of_bins, ...
        number_of_bins);

    sample_count = reshape( ...
        count_vector, ...
        number_of_bins, ...
        number_of_bins);

    metric_map(sample_count < minimum_sample_count) = NaN;
end

function plotHeatmapGroup( ...
        k1_centers, d1_centers, k1_d1_map, ...
        k_theta_centers, d_theta_centers, ktheta_dtheta_map, ...
        nominal_gains, reference_limit, statistic_name, ...
        figure_title, colorbar_label)

    all_finite_values = [
        k1_d1_map(isfinite(k1_d1_map));
        ktheta_dtheta_map(isfinite(ktheta_dtheta_map))
    ];

    if isempty(all_finite_values)
        color_limits = [];
    else
        color_limits = [
            min(all_finite_values), ...
            max(all_finite_values)
        ];

        if color_limits(1) == color_limits(2)
            padding = max(1e-12, 0.01*abs(color_limits(1)));
            color_limits = color_limits + [-padding, padding];
        end
    end

    figure( ...
        'Name', figure_title, ...
        'Color', 'w');

    tiledlayout( ...
        1, 2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    axes_1 = nexttile;

    plotSingleHeatmap( ...
        axes_1, ...
        k1_centers, ...
        d1_centers, ...
        k1_d1_map, ...
        nominal_gains(1), ...
        nominal_gains(2), ...
        reference_limit, ...
        color_limits, ...
        'k1 (N/m)', ...
        'd1 (N s/m)', ...
        sprintf('(k1, d1), %s over other gains', statistic_name), ...
        colorbar_label);

    axes_2 = nexttile;

    plotSingleHeatmap( ...
        axes_2, ...
        k_theta_centers, ...
        d_theta_centers, ...
        ktheta_dtheta_map, ...
        nominal_gains(3), ...
        nominal_gains(4), ...
        reference_limit, ...
        color_limits, ...
        'k_theta (N/rad)', ...
        'd_theta (N s/rad)', ...
        sprintf( ...
            '(k_theta, d_theta), %s over other gains', ...
            statistic_name), ...
        colorbar_label);

    sgtitle(figure_title, 'Interpreter', 'none');
end

function plotSingleHeatmap( ...
        axes_handle, x_centers, y_centers, metric_map, ...
        nominal_x, nominal_y, reference_limit, color_limits, ...
        x_label, y_label, tile_title, colorbar_label)

    image_handle = imagesc( ...
        axes_handle, ...
        x_centers, ...
        y_centers, ...
        metric_map);

    set(axes_handle, ...
        'YDir', 'normal', ...
        'Color', [0.82, 0.82, 0.82], ...
        'Layer', 'top');

    set(image_handle, ...
        'AlphaData', isfinite(metric_map));

    colormap(axes_handle, parula(256));

    if ~isempty(color_limits)
        caxis(axes_handle, color_limits);
    end

    colorbar_handle = colorbar(axes_handle);
    colorbar_handle.Label.String = colorbar_label;
    colorbar_handle.Label.Interpreter = 'none';

    hold(axes_handle, 'on');

    finite_values = metric_map(isfinite(metric_map));
    legend_handles = gobjects(0, 1);

    if ~isempty(finite_values) && ...
       min(finite_values) <= reference_limit && ...
       max(finite_values) >= reference_limit

        [~, limit_contour] = contour( ...
            axes_handle, ...
            x_centers, ...
            y_centers, ...
            metric_map, ...
            [reference_limit, reference_limit], ...
            'k--', ...
            'LineWidth', 1.8, ...
            'DisplayName', 'Hardware limit');

        legend_handles(end + 1) = limit_contour;
    end

    if nominal_x >= min(x_centers) && ...
       nominal_x <= max(x_centers) && ...
       nominal_y >= min(y_centers) && ...
       nominal_y <= max(y_centers)

        nominal_marker = plot( ...
            axes_handle, ...
            nominal_x, ...
            nominal_y, ...
            'wo', ...
            'MarkerFaceColor', 'k', ...
            'MarkerSize', 7, ...
            'LineWidth', 1.3, ...
            'DisplayName', 'Current gains');

        legend_handles(end + 1) = nominal_marker;
    end

    grid(axes_handle, 'on');
    box(axes_handle, 'on');

    xlabel(axes_handle, x_label, 'Interpreter', 'none');
    ylabel(axes_handle, y_label, 'Interpreter', 'none');
    title(axes_handle, tile_title, 'Interpreter', 'none');

    if ~isempty(legend_handles)
        legend( ...
            axes_handle, ...
            legend_handles, ...
            'Location', ...
            'best');
    end

    hold(axes_handle, 'off');
end
