clear;
clc;
close all;

addpath("param/", "model/");

par = LatParam();

m = par.m_rod;
R = par.R;
g = par.g;
G = par.G;

C_eq = (G + m*g*R)/(m*g);

force_limit = 100000;
rod_limit = 10;

k1 = 700;      % N/m
d1 = 50;       % N*s/m

ktheta = 20;
kdtheta = 3;

theta0 = 0.10;  % rad
r0 = 0.00;      % m

z0 = [
    theta0;
    0;
    r0;
    0
];

fprintf('Initial condition:\n');
fprintf('  theta0       = %.6f rad\n', theta0);
fprintf('  r0           = %.6f m\n', r0);
fprintf('  r_eq(theta0) = %.6f m\n\n', C_eq*tan(theta0));

tspan = [0, 30];

ode_options = odeset( ...
    'RelTol', 1e-8, ...
    'AbsTol', 1e-10, ...
    'MaxStep', 0.002);

chunk_duration = 0.02;  % s

%% 5. Define controller

controller = @(t, z, p) equilibriumCurveController( ...
    t, ...
    z, ...
    p, ...
    C_eq, ...
    k1, ...
    d1, ...
    ktheta, ...
    kdtheta, ...
    force_limit);

%% 6. Simulate

fprintf('Equilibrium-curve controller\n');
fprintf('  k1       = %.3f N/m\n', k1);
fprintf('  d1       = %.3f N*s/m\n', d1);
fprintf('  ktheta   = %.3f\n', ktheta);
fprintf('  kdtheta  = %.3f\n\n', kdtheta);

result = simulateController( ...
    par, ...
    controller, ...
    z0, ...
    tspan, ...
    ode_options, ...
    chunk_duration, ...
    C_eq, ...
    force_limit, ...
    rod_limit);

%% 7. Plot

figure_title = sprintf( ...
    'Equilibrium-curve controller, k_1 = %.0f', ...
    k1);

plotControllerResult( ...
    result, ...
    C_eq, ...
    theta0, ...
    r0, ...
    figure_title, ...
    [0.0000, 0.4470, 0.7410]);

%% 8. Final summary

printResultSummary( ...
    'Equilibrium-curve controller', ...
    result);

%% ========================================================================
% Local functions
% ========================================================================

function F = equilibriumCurveController( ...
        ~, ...
        z, ...
        par, ...
        C_eq, ...
        k1, ...
        d1, ...
        ktheta, ...
        kdtheta, ...
        force_limit)

    theta = z(1);
    theta_dot = z(2);
    r = z(3);
    r_dot = z(4);

    sec2_theta = 1/(cos(theta)^2);

    % Equilibrium-curve error
    s = ...
        r ...
        - C_eq*tan(theta);

    % Time derivative of equilibrium-curve error
    s_dot = ...
        r_dot ...
        - C_eq*sec2_theta*theta_dot;

    % Controller
    F_unsaturated = ...
        par.m_rod*par.g*sin(theta) ...
        - k1*s ...
        - d1*s_dot ...
        + ktheta*theta ...
        + kdtheta*theta_dot;

    F = saturateForce( ...
        F_unsaturated, ...
        force_limit);

end

%% ========================================================================

function result = simulateController( ...
        par, ...
        controller, ...
        z0, ...
        tspan, ...
        ode_options, ...
        chunk_duration, ...
        C_eq, ...
        force_limit, ...
        rod_limit)

    model_rhs = @(t, z) LatModel_SignCorrection( ...
        t, ...
        z, ...
        par, ...
        controller);

    t_all = tspan(1);
    z_all = z0(:).';

    t_current = tspan(1);
    z_current = z0(:);

    stopped_early = false;
    stop_message = '';

    while t_current < tspan(end)

        t_segment_end = min( ...
            t_current + chunk_duration, ...
            tspan(end));

        try

            [t_segment, z_segment] = ode45( ...
                model_rhs, ...
                [t_current, t_segment_end], ...
                z_current, ...
                ode_options);

        catch ME

            stopped_early = true;
            stop_message = ME.message;

            fprintf( ...
                'Model stopped at t = %.6f s: %s\n', ...
                t_current, ...
                ME.message);

            break;

        end

        %% Check NaN / Inf

        if any(~isfinite(t_segment(:))) || ...
           any(~isfinite(z_segment(:)))

            stopped_early = true;

            stop_message = ...
                'NaN or Inf appeared in the simulation.';

            fprintf( ...
                'NaN or Inf detected at t = %.6f s.\n', ...
                t_current);

            break;

        end

        %% Store result

        if length(t_segment) > 1

            t_all = [
                t_all;
                t_segment(2:end)
            ];

            z_all = [
                z_all;
                z_segment(2:end, :)
            ];

        end

        previous_time = t_current;

        t_current = t_segment(end);
        z_current = z_segment(end, :).';

        %% Check rod limit

        if abs(z_current(3)) > rod_limit

            stopped_early = true;

            stop_message = ...
                'The rod-position limit was exceeded.';

            fprintf( ...
                'Rod limit exceeded at t = %.6f s.\n', ...
                t_current);

            break;

        end

        %% Check whether ODE solver advanced

        time_tolerance = ...
            10*eps(max(1, abs(previous_time)));

        if t_current <= previous_time + time_tolerance

            stopped_early = true;

            stop_message = ...
                'ode45 returned without advancing time.';

            fprintf( ...
                'ode45 did not advance past t = %.6f s.\n', ...
                t_current);

            break;

        end

        %% Check whether full segment was completed

        segment_tolerance = ...
            1e-10*max(1, abs(t_segment_end));

        if t_current < t_segment_end - segment_tolerance

            stopped_early = true;

            stop_message = ...
                'ode45 returned before the requested segment endpoint.';

            fprintf( ...
                'ode45 returned early at t = %.6f s.\n', ...
                t_current);

            break;

        end

    end

    %% Extract states

    theta = z_all(:, 1);
    theta_dot = z_all(:, 2);

    r = z_all(:, 3);
    r_dot = z_all(:, 4);

    %% Equilibrium curve

    r_eq = ...
        C_eq*tan(theta);

    r_eq_dot = ...
        C_eq./(cos(theta).^2).*theta_dot;

    %% Surface error

    s = ...
        r ...
        - r_eq;

    s_dot = ...
        r_dot ...
        - r_eq_dot;

    %% Reconstruct control force

    F = nan(size(t_all));

    for i = 1:length(t_all)

        try

            F(i) = controller( ...
                t_all(i), ...
                z_all(i, :).', ...
                par);

        catch

            F(i) = NaN;

        end

    end

    F = max( ...
        -force_limit, ...
        min(force_limit, F));

    %% Save results

    result.t = t_all;
    result.z = z_all;

    result.r_eq = r_eq;
    result.r_eq_dot = r_eq_dot;

    result.s = s;
    result.s_dot = s_dot;

    result.F = F;

    result.stopped_early = stopped_early;
    result.stop_message = stop_message;

    %% Print simulation status

    if stopped_early

        fprintf( ...
            'Simulation stopped early at t = %.6f s.\n', ...
            t_all(end));

    else

        fprintf( ...
            'Simulation completed at t = %.6f s.\n', ...
            t_all(end));

    end

end

%% ========================================================================

function plotControllerResult( ...
        result, ...
        C_eq, ...
        theta0, ...
        r0, ...
        figure_title, ...
        line_color)

    figure( ...
        'Name', figure_title, ...
        'Color', 'w');

    tiledlayout( ...
        3, ...
        2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    %% Lean angle

    nexttile;

    plot( ...
        result.t, ...
        result.z(:, 1), ...
        'Color', line_color, ...
        'LineWidth', 1.6);

    yline(0, '--k');

    grid on;
    box on;

    xlabel( ...
        '$t\;({\rm s})$', ...
        'Interpreter', 'latex');

    ylabel( ...
        '$\theta\;({\rm rad})$', ...
        'Interpreter', 'latex');

    title( ...
        'Lean angle', ...
        'Interpreter', 'latex');

    %% Rod position

    nexttile;

    plot( ...
        result.t, ...
        result.z(:, 3), ...
        'Color', line_color, ...
        'LineWidth', 1.6);

    yline(0, '--k');

    grid on;
    box on;

    xlabel( ...
        '$t\;({\rm s})$', ...
        'Interpreter', 'latex');

    ylabel( ...
        '$r\;({\rm m})$', ...
        'Interpreter', 'latex');

    title( ...
        'Rod position', ...
        'Interpreter', 'latex');

    %% Surface error

    nexttile;

    plot( ...
        result.t, ...
        result.s, ...
        'Color', line_color, ...
        'LineWidth', 1.6);

    yline(0, '--k');

    grid on;
    box on;

    xlabel( ...
        '$t\;({\rm s})$', ...
        'Interpreter', 'latex');

    ylabel( ...
        '$s\;({\rm m})$', ...
        'Interpreter', 'latex');

    title( ...
        '$s=r-C\tan\theta$', ...
        'Interpreter', 'latex');

    %% Surface velocity

    nexttile;

    plot( ...
        result.t, ...
        result.s_dot, ...
        'Color', line_color, ...
        'LineWidth', 1.6);

    yline(0, '--k');

    grid on;
    box on;

    xlabel( ...
        '$t\;({\rm s})$', ...
        'Interpreter', 'latex');

    ylabel( ...
        '$\dot{s}\;({\rm m/s})$', ...
        'Interpreter', 'latex');

    title( ...
        'Surface velocity', ...
        'Interpreter', 'latex');

    %% Control force

    nexttile;

    plot( ...
        result.t, ...
        result.F, ...
        'Color', line_color, ...
        'LineWidth', 1.6);

    yline(0, '--k');

    grid on;
    box on;

    xlabel( ...
        '$t\;({\rm s})$', ...
        'Interpreter', 'latex');

    ylabel( ...
        '$F\;({\rm N})$', ...
        'Interpreter', 'latex');

    title( ...
        'Control force', ...
        'Interpreter', 'latex');

    %% theta-r plane

    nexttile;

    hold on;
    grid on;
    box on;

    theta_bound = max([ ...
        0.15, ...
        1.15*max(abs(result.z(:, 1))), ...
        1.15*abs(theta0)]);

    theta_bound = min( ...
        theta_bound, ...
        0.95*pi/2);

    theta_curve = linspace( ...
        -theta_bound, ...
        theta_bound, ...
        600);

    %% Equilibrium curve

    plot( ...
        theta_curve, ...
        C_eq*tan(theta_curve), ...
        '--k', ...
        'LineWidth', 1.8, ...
        'DisplayName', '$r=C\tan\theta$');

    %% Simulated trajectory

    plot( ...
        result.z(:, 1), ...
        result.z(:, 3), ...
        'Color', line_color, ...
        'LineWidth', 1.8, ...
        'DisplayName', 'Trajectory');

    %% Initial state

    plot( ...
        theta0, ...
        r0, ...
        'ko', ...
        'MarkerFaceColor', 'y', ...
        'MarkerSize', 7, ...
        'DisplayName', 'Initial state');

    %% Final state

    plot( ...
        result.z(end, 1), ...
        result.z(end, 3), ...
        'kx', ...
        'LineWidth', 1.7, ...
        'MarkerSize', 8, ...
        'DisplayName', 'Final state');

    xlabel( ...
        '$\theta\;({\rm rad})$', ...
        'Interpreter', 'latex');

    ylabel( ...
        '$r\;({\rm m})$', ...
        'Interpreter', 'latex');

    title( ...
        'Trajectory in the $(\theta,r)$ plane', ...
        'Interpreter', 'latex');

    legend( ...
        'Location', 'best', ...
        'Interpreter', 'latex');

    hold off;

    sgtitle( ...
        figure_title, ...
        'Interpreter', 'none');

end

%% ========================================================================

function printResultSummary(name, result)

    final_state = result.z(end, :);

    finite_force = ...
        result.F(isfinite(result.F));

    if isempty(finite_force)

        max_force = NaN;

    else

        max_force = ...
            max(abs(finite_force));

    end

    fprintf( ...
        '\n%s final valid state:\n', ...
        name);

    fprintf( ...
        '  t             = %.6f s\n', ...
        result.t(end));

    fprintf( ...
        '  theta         = %+12.6f rad\n', ...
        final_state(1));

    fprintf( ...
        '  theta_dot     = %+12.6f rad/s\n', ...
        final_state(2));

    fprintf( ...
        '  r             = %+12.6f m\n', ...
        final_state(3));

    fprintf( ...
        '  r_dot         = %+12.6f m/s\n', ...
        final_state(4));

    fprintf( ...
        '  s             = %+12.6f m\n', ...
        result.s(end));

    fprintf( ...
        '  max|F|        = %.6f N\n', ...
        max_force);

    if result.stopped_early

        fprintf( ...
            '  status        = stopped early\n');

        fprintf( ...
            '  stop message  = %s\n', ...
            result.stop_message);

    else

        fprintf( ...
            '  status        = completed\n');

    end

end

%% ========================================================================

function F = saturateForce(F, force_limit)

    F = max( ...
        -force_limit, ...
        min(force_limit, F));

end