clear;
clc;
close all;

addpath("param/", "model/");

%% 1. System parameters

par = LatParam();

m = par.m_rod;
R = par.R;
g = par.g;
G = par.G;

%% 2. Equilibrium curve

equilibrium_factor = ...
    (G + m*g*R)/(m*g);

%% 3. Open-loop linearization at the upright equilibrium
%
% Open loop: F = 0
%
% State order:
% z = [theta; theta_dot; r; r_dot]

z_equilibrium = zeros(4, 1);
fd_step = 1e-6;

zero_force_controller = @(t, z, par) 0;

open_loop_rhs = @(z) ...
    LatModel_SignCorrection( ...
        0, ...
        z, ...
        par, ...
        zero_force_controller);

A_open_loop = zeros(4, 4);

for i = 1:4
    dz = zeros(4, 1);
    dz(i) = fd_step;

    A_open_loop(:, i) = ...
        (open_loop_rhs(z_equilibrium + dz) ...
        - open_loop_rhs(z_equilibrium - dz)) ...
        /(2*fd_step);
end

[V_open_loop, D_open_loop] = ...
    eig(A_open_loop);

lambda_open_loop = ...
    diag(D_open_loop);

% Sort according to the real part of each eigenvalue.
[~, eigen_order] = sort( ...
    real(lambda_open_loop), ...
    'descend');

lambda_open_loop = ...
    lambda_open_loop(eigen_order);

V_open_loop = ...
    V_open_loop(:, eigen_order);

% Extract the theta-r projection of every eigenvector.
V_theta_r = zeros(2, 4);

for i = 1:4
    v = V_open_loop(:, i);
    q_part = v([1, 3]);

    % Rotate a complex eigenvector so its largest configuration
    % component becomes real.
    [~, pivot_index] = ...
        max(abs(q_part));

    if abs(q_part(pivot_index)) > 1e-12
        v = v*exp( ...
            -1i*angle(q_part(pivot_index)));
    end

    direction = ...
        real(v([1, 3]));

    if norm(direction) < 1e-12
        direction = ...
            imag(v([1, 3]));
    end

    if norm(direction) > 1e-12
        direction = ...
            direction/norm(direction);
    end

    % Consistent eigenvector sign.
    if abs(direction(1)) > 1e-12
        if direction(1) < 0
            direction = -direction;
        end
    elseif direction(2) < 0
        direction = -direction;
    end

    V_theta_r(:, i) = direction;
end

fprintf( ...
    'Open-loop A matrix at the upright equilibrium:\n');
disp(A_open_loop);

fprintf( ...
    'Open-loop eigenvalues and theta-r directions:\n');

for i = 1:4
    fprintf( ...
        ['  v%d: lambda = %+12.6f %+12.6fi, ', ...
         '[theta; r] = [%+10.6f; %+10.6f]'], ...
        i, ...
        real(lambda_open_loop(i)), ...
        imag(lambda_open_loop(i)), ...
        V_theta_r(1, i), ...
        V_theta_r(2, i));

    if abs(V_theta_r(1, i)) > 1e-12
        fprintf( ...
            ', r/theta = %+10.6f\n', ...
            V_theta_r(2, i) ...
            /V_theta_r(1, i));
    else
        fprintf(', r/theta = Inf\n');
    end
end

%% 4. Controller settings
%
% F = m*g*sin(theta)
%     + k*(r-r_eq(theta))

k_values = [
    -200, ...
    -300, ...
    -500, ...
    -800, ...
];  % N/m

num_cases = length(k_values);
case_colors = lines(num_cases);

%% 5. Initial condition
%
% State order:
% z = [theta; theta_dot; r; r_dot]

theta0 = 0.10;  % rad
r0 = 0.00;      % m

z0 = [
    theta0;
    0;
    r0;
    0
];

r_eq_initial = ...
    equilibrium_factor*tan(theta0);

fprintf('Initial condition:\n');
fprintf('  theta0          = %.6f rad\n', theta0);
fprintf('  r0              = %.6f m\n', r0);
fprintf( ...
    '  r_eq(theta0)    = %.6f m\n', ...
    r_eq_initial);
fprintf( ...
    '  initial r error = %.6f m\n\n', ...
    r0-r_eq_initial);

%% 6. Simulation settings

tspan = [0, 2];

ode_options = odeset( ...
    'RelTol', 1e-8, ...
    'AbsTol', 1e-10, ...
    'MaxStep', 0.002);

chunk_duration = 0.02;

%% 7. Allocate simulation results

results = struct( ...
    'k', cell(num_cases, 1), ...
    't', cell(num_cases, 1), ...
    'z', cell(num_cases, 1), ...
    'r_eq', cell(num_cases, 1), ...
    'r_error', cell(num_cases, 1), ...
    'F', cell(num_cases, 1), ...
    'stopped_early', cell(num_cases, 1), ...
    'stop_message', cell(num_cases, 1));

%% 8. Simulate different k values

for j = 1:num_cases

    k = k_values(j);

    fprintf( ...
        'Simulating k = %+7.1f N/m...\n', ...
        k);

    controller = @(t, z, par) ...
        par.m_rod*par.g*sin(z(1)) ...
        + k*( ...
            z(3) ...
            - equilibrium_factor*tan(z(1)) ...
        );

    model_rhs = @(t, z) ...
        LatModel_SignCorrection( ...
            t, z, par, controller);

    t_all = tspan(1);
    z_all = z0(:).';

    t_current = tspan(1);
    z_current = z0(:);

    stopped_early = false;
    stop_message = '';

    while t_current < tspan(end)

        t_segment_end = min( ...
            t_current + chunk_duration, ...
            tspan(end));

        try
            [t_segment, z_segment] = ode45( ...
                model_rhs, ...
                [t_current, t_segment_end], ...
                z_current, ...
                ode_options);

        catch ME
            stopped_early = true;
            stop_message = ME.message;

            fprintf( ...
                ['  Model error at t = %.6f s.\n', ...
                 '  Last valid state was retained.\n', ...
                 '  Error: %s\n'], ...
                t_current, ...
                ME.message);

            break;
        end

        if any(~isfinite(t_segment(:))) || ...
           any(~isfinite(z_segment(:)))

            stopped_early = true;
            stop_message = ...
                'NaN or Inf appeared in the simulation.';

            fprintf( ...
                ['  NaN or Inf detected at ', ...
                 't = %.6f s.\n'], ...
                t_current);

            break;
        end

        if length(t_segment) > 1
            t_all = [
                t_all;
                t_segment(2:end)
            ];

            z_all = [
                z_all;
                z_segment(2:end, :)
            ];
        end

        previous_time = t_current;

        t_current = t_segment(end);
        z_current = z_segment(end, :).';

        time_tolerance = ...
            10*eps(max(1, abs(previous_time)));

        if t_current <= ...
                previous_time + time_tolerance

            stopped_early = true;
            stop_message = ...
                'ode45 returned without advancing time.';

            fprintf( ...
                ['  ode45 did not advance past ', ...
                 't = %.6f s.\n'], ...
                t_current);

            break;
        end

        segment_tolerance = ...
            1e-10*max(1, abs(t_segment_end));

        if t_current < ...
                t_segment_end-segment_tolerance

            stopped_early = true;
            stop_message = ...
                ['ode45 returned before reaching ', ...
                 'the requested segment endpoint.'];

            fprintf( ...
                ['  ode45 returned early at ', ...
                 't = %.6f s.\n'], ...
                t_current);

            break;
        end
    end

    %% Process valid data

    t_out = t_all;
    z_out = z_all;

    theta_out = z_out(:, 1);
    r_out = z_out(:, 3);

    r_eq_out = ...
        equilibrium_factor*tan(theta_out);

    r_error_out = ...
        r_out-r_eq_out;

    F_out = ...
        m*g*sin(theta_out) ...
        + k*r_error_out;

    results(j).k = k;
    results(j).t = t_out;
    results(j).z = z_out;
    results(j).r_eq = r_eq_out;
    results(j).r_error = r_error_out;
    results(j).F = F_out;
    results(j).stopped_early = stopped_early;
    results(j).stop_message = stop_message;

    if stopped_early
        fprintf( ...
            ['  k = %+7.1f N/m stopped early ', ...
             'at t = %.6f s.\n\n'], ...
            k, ...
            t_out(end));
    else
        fprintf( ...
            ['  k = %+7.1f N/m successfully ', ...
             'reached t = %.6f s.\n\n'], ...
            k, ...
            t_out(end));
    end
end

%% 9. Time-history plots

figure( ...
    'Name', ...
    'Current-theta equilibrium controller', ...
    'Color', 'w');

subplot(4, 1, 1);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).z(:, 1), ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5, ...
        'DisplayName', sprintf( ...
            'k = %+g N/m', ...
            results(j).k));
end

yline( ...
    0, ...
    '--k', ...
    'Upright', ...
    'HandleVisibility', 'off');

ylabel( ...
    '$\theta\;(\mathrm{rad})$', ...
    'Interpreter', 'latex');

title( ...
    ['$F=m_{\mathrm{rod}}g\sin\theta', ...
     '+k\left(r-r_{\mathrm{eq}}(\theta)\right)$'], ...
    'Interpreter', 'latex');

legend('Location', 'eastoutside');

hold off;

subplot(4, 1, 2);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).z(:, 3), ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5);
end

ylabel( ...
    '$r\;(\mathrm{m})$', ...
    'Interpreter', 'latex');

hold off;

subplot(4, 1, 3);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).r_error, ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5);
end

yline( ...
    0, ...
    '--k', ...
    'Equilibrium curve');

ylabel( ...
    '$r-r_{\mathrm{eq}}(\theta)\;(\mathrm{m})$', ...
    'Interpreter', 'latex');

hold off;

subplot(4, 1, 4);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).F, ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5);
end

xlabel( ...
    '$t\;(\mathrm{s})$', ...
    'Interpreter', 'latex');

ylabel( ...
    '$F\;(\mathrm{N})$', ...
    'Interpreter', 'latex');

hold off;

%% 10. Theta-r trajectories and open-loop eigenvectors

figure( ...
    'Name', ...
    'Trajectories and open-loop eigenvectors', ...
    'Color', 'w');

hold on;
grid on;
box on;

theta_curve = ...
    linspace(-0.25, 0.25, 600);

r_curve = ...
    equilibrium_factor*tan(theta_curve);

plot( ...
    theta_curve, ...
    r_curve, ...
    '--k', ...
    'LineWidth', 2, ...
    'DisplayName', ...
    '$r_{\mathrm{eq}}(\theta)$');

%% Simulated trajectories

for j = 1:num_cases

    plot( ...
        results(j).z(:, 1), ...
        results(j).z(:, 3), ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5, ...
        'DisplayName', sprintf( ...
            '$k=%+g$ N/m', ...
            results(j).k));

    plot( ...
        results(j).z(end, 1), ...
        results(j).z(end, 3), ...
        'x', ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5, ...
        'MarkerSize', 8, ...
        'HandleVisibility', 'off');
end

plot( ...
    theta0, ...
    r0, ...
    'ko', ...
    'MarkerFaceColor', 'y', ...
    'MarkerSize', 8, ...
    'DisplayName', ...
    'Initial state');

%% Open-loop eigenvectors
%
% Different lengths are used so that eigenvectors with identical
% theta-r directions remain visible.

eigenvector_colors = lines(4);

eigenvector_lengths = [
    0.16;
    0.14;
    0.12;
    0.10
];

eigenvalue_text = cell(4, 1);

for i = 1:4

    arrow = ...
        eigenvector_lengths(i)*V_theta_r(:, i);

    lambda_real = ...
        real(lambda_open_loop(i));

    lambda_imag = ...
        imag(lambda_open_loop(i));

    if abs(lambda_imag) < 1e-10

        lambda_value_text = ...
            sprintf( ...
                '%+.4f', ...
                lambda_real);

    else

        lambda_value_text = ...
            sprintf( ...
                '%+.4f%+.4fi', ...
                lambda_real, ...
                lambda_imag);
    end

    % Construct LaTeX outside sprintf so backslashes are not
    % interpreted as sprintf escape sequences.
    eigenvector_label = [
        '$v_{', ...
        num2str(i), ...
        '},\;\lambda=', ...
        lambda_value_text, ...
        '$'
    ];

    eigenvalue_text{i} = [
        '$\lambda_{', ...
        num2str(i), ...
        '}=', ...
        lambda_value_text, ...
        '$'
    ];

    % Positive direction
    quiver( ...
        0, ...
        0, ...
        arrow(1), ...
        arrow(2), ...
        0, ...
        'Color', eigenvector_colors(i, :), ...
        'LineWidth', 2.2, ...
        'MaxHeadSize', 0.25, ...
        'DisplayName', eigenvector_label);

    % Negative direction
    quiver( ...
        0, ...
        0, ...
        -arrow(1), ...
        -arrow(2), ...
        0, ...
        'Color', eigenvector_colors(i, :), ...
        'LineWidth', 2.2, ...
        'MaxHeadSize', 0.25, ...
        'HandleVisibility', 'off');

    text( ...
        arrow(1), ...
        arrow(2), ...
        sprintf('  v_%d', i), ...
        'Color', eigenvector_colors(i, :), ...
        'FontWeight', 'bold', ...
        'Interpreter', 'tex');
end

%% Eigenvalue text box inside Figure 2

text( ...
    0.02, ...
    0.98, ...
    eigenvalue_text, ...
    'Units', 'normalized', ...
    'VerticalAlignment', 'top', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'w', ...
    'EdgeColor', [0.4, 0.4, 0.4], ...
    'Margin', 6, ...
    'Interpreter', 'latex');

xlabel( ...
    '$\theta\;(\mathrm{rad})$', ...
    'Interpreter', 'latex');

ylabel( ...
    '$r\;(\mathrm{m})$', ...
    'Interpreter', 'latex');

title( ...
    ['Motion relative to the equilibrium curve ', ...
     'and open-loop eigenvectors'], ...
    'Interpreter', 'latex');

legend( ...
    'Location', 'eastoutside', ...
    'Interpreter', 'latex');

hold off;