% Fixed-gain nonlinear simulation with static and dynamic
% BNO085 measurement errors.
%
% State ordering:
%
% z = [theta; theta_dot; r; r_dot]
%
% Measurement model:
%
% theta_measured =
%     theta_true
%     + static_angle_bias
%     + dynamic_angle_error
%
% theta_dot_measured =
%     theta_dot_true
%     + dynamic_gyro_error
%
% The static angle bias remains constant during one simulation.
%
% The dynamic errors are generated using first-order
% Gauss-Markov colored-noise models.
%
% Controller:
%
% F = -(K_theta*theta_measured
%     + K_theta_dot*theta_dot_measured
%     + K_r*r
%     + K_r_dot*r_dot)

clear;
clc;
close all;

addpath("param/", "model/");

%% 1. Load system parameters

par = LatParam();

%% 2. Fixed controller gains

par.K_theta     = -781.4476;
par.K_theta_dot = -146.7735;
par.K_r         =  229.6972;
par.K_r_dot     =   41.4447;

% State ordering:
% [theta, theta_dot, r, r_dot]
K = [
    par.K_theta, ...
    par.K_theta_dot, ...
    par.K_r, ...
    par.K_r_dot
];

disp("Fixed controller gain:");
disp(K);

%% 3. Simulation settings

sample_frequency_Hz = 100;
dt = 1/sample_frequency_Hz;

t_end = 15;
t_out = (0:dt:t_end)';

number_of_steps = length(t_out);

% Initial condition:
% z = [theta; theta_dot; r; r_dot]
z0 = [
    0; 
    0;
    0;
    0
];

% Repeatable random sequence.
rng(1);

%% 4. BNO085 nominal error values

% Values from the BNO08X datasheet for the
% Gaming Rotation Vector:
%
% Static non-heading error  = 1.5 deg
% Dynamic non-heading error = 2.5 deg
%
% Gyroscope nominal dynamic accuracy = 3.1 deg/s

BNO_static_angle_error_deg = 1.5;
BNO_dynamic_angle_error_deg = 2.5;
BNO_dynamic_gyro_error_degps = 3.1;

%% 5. Error scale cases

% Each case represents a fraction of the nominal BNO085
% performance error.
%
% The last case, scale = 1.0, uses:
%
% static angle bias      = 1.5 deg
% dynamic angle limit    = 2.5 deg
% dynamic gyro limit     = 3.1 deg/s

error_scale_values = [
    0.00, ...
    0.10, ...
    0.20, ...
    0.40, ...
    0.70, ...
    1.00
];

number_of_cases = length(error_scale_values);

static_angle_bias_deg_values = ...
    error_scale_values*BNO_static_angle_error_deg;

dynamic_angle_limit_deg_values = ...
    error_scale_values*BNO_dynamic_angle_error_deg;

dynamic_gyro_limit_degps_values = ...
    error_scale_values*BNO_dynamic_gyro_error_degps;

%% 6. Static bias direction

% Use +1 for positive static bias.
% Use -1 for negative static bias.
%
% Both directions should eventually be tested because the
% available rod travel may not be symmetric.

static_bias_sign = 1;

static_angle_bias_deg_values = ...
    static_bias_sign*static_angle_bias_deg_values;

%% 7. Dynamic colored-noise settings

% Correlation time for the fused angle error.
%
% Larger value:
% dynamic error changes more slowly.
%
% Smaller value:
% dynamic error changes more quickly.
dynamic_angle_tau_s = 0.25;

% Correlation time for the gyroscope error.
dynamic_gyro_tau_s = 0.10;

rho_angle = exp(-dt/dynamic_angle_tau_s);
rho_gyro = exp(-dt/dynamic_gyro_tau_s);

% The datasheet does not specify whether its nominal error is
% RMS, standard deviation or a strict maximum.
%
% Here the nominal dynamic error is interpreted as about
% three standard deviations.
datasheet_error_sigma_divisor = 3;

%% 8. Physical force limit

use_force_limit = true;

force_limit_N = 27.5;

%% 9. Allocate simulation results

z_all = nan( ...
    number_of_steps, ...
    4, ...
    number_of_cases ...
);

F_all = nan( ...
    number_of_steps, ...
    number_of_cases ...
);

F_unlimited_all = nan( ...
    number_of_steps, ...
    number_of_cases ...
);

theta_measured_all = nan( ...
    number_of_steps, ...
    number_of_cases ...
);

theta_dot_measured_all = nan( ...
    number_of_steps, ...
    number_of_cases ...
);

static_angle_error_all = zeros( ...
    number_of_steps, ...
    number_of_cases ...
);

dynamic_angle_error_all = zeros( ...
    number_of_steps, ...
    number_of_cases ...
);

dynamic_gyro_error_all = zeros( ...
    number_of_steps, ...
    number_of_cases ...
);

force_saturated_all = false( ...
    number_of_steps, ...
    number_of_cases ...
);

simulation_failed = false( ...
    number_of_cases, ...
    1 ...
);

%% 10. Run all error cases

for case_index = 1:number_of_cases

    % Static bias remains constant throughout this entire case.
    static_angle_bias = ...
        static_angle_bias_deg_values(case_index)*pi/180;

    % Maximum dynamic errors.
    dynamic_angle_limit = ...
        abs(dynamic_angle_limit_deg_values(case_index))*pi/180;

    dynamic_gyro_limit = ...
        abs(dynamic_gyro_limit_degps_values(case_index))*pi/180;

    % Interpret the nominal limits as approximately 3 sigma.
    sigma_dynamic_angle = ...
        dynamic_angle_limit/datasheet_error_sigma_divisor;

    sigma_dynamic_gyro = ...
        dynamic_gyro_limit/datasheet_error_sigma_divisor;

    % Increment standard deviations required to obtain the
    % desired stationary Gauss-Markov standard deviations.
    sigma_angle_increment = ...
        sigma_dynamic_angle*sqrt(1-rho_angle^2);

    sigma_gyro_increment = ...
        sigma_dynamic_gyro*sqrt(1-rho_gyro^2);

    % Reset dynamic error states.
    dynamic_angle_error = 0;
    dynamic_gyro_error = 0;

    % Reset physical state.
    z = z0;

    z_all(1,:,case_index) = z';

    for k = 1:number_of_steps

        current_time = t_out(k);

        % Update the dynamic angle error.
        dynamic_angle_error = ...
            rho_angle*dynamic_angle_error + ...
            sigma_angle_increment*randn;

        % Limit the dynamic angle error to the nominal range.
        if dynamic_angle_limit > 0

            dynamic_angle_error = max( ...
                -dynamic_angle_limit, ...
                min( ...
                    dynamic_angle_limit, ...
                    dynamic_angle_error ...
                ) ...
            );
        else
            dynamic_angle_error = 0;
        end

        % Update the dynamic gyroscope error.
        dynamic_gyro_error = ...
            rho_gyro*dynamic_gyro_error + ...
            sigma_gyro_increment*randn;

        % Limit the gyroscope error to the nominal range.
        if dynamic_gyro_limit > 0

            dynamic_gyro_error = max( ...
                -dynamic_gyro_limit, ...
                min( ...
                    dynamic_gyro_limit, ...
                    dynamic_gyro_error ...
                ) ...
            );
        else
            dynamic_gyro_error = 0;
        end

        % Total angle measurement error.
        total_angle_error = ...
            static_angle_bias + ...
            dynamic_angle_error;

        % Total angular-velocity measurement error.
        total_gyro_error = dynamic_gyro_error;

        % Construct the measured states.
        theta_measured = ...
            z(1) + total_angle_error;

        theta_dot_measured = ...
            z(2) + total_gyro_error;

        z_measured = [
            theta_measured;
            theta_dot_measured;
            z(3);
            z(4)
        ];

        % Unlimited controller force request.
        F_unlimited = -K*z_measured;

        % Apply physical force limit.
        if use_force_limit

            F_command = max( ...
                -force_limit_N, ...
                min(force_limit_N, F_unlimited) ...
            );
        else
            F_command = F_unlimited;
        end

        force_saturated = ...
            abs(F_unlimited) > force_limit_N;

        % Save measurements and control values.
        theta_measured_all(k,case_index) = ...
            theta_measured;

        theta_dot_measured_all(k,case_index) = ...
            theta_dot_measured;

        static_angle_error_all(k,case_index) = ...
            static_angle_bias;

        dynamic_angle_error_all(k,case_index) = ...
            dynamic_angle_error;

        dynamic_gyro_error_all(k,case_index) = ...
            dynamic_gyro_error;

        F_all(k,case_index) = F_command;

        F_unlimited_all(k,case_index) = F_unlimited;

        force_saturated_all(k,case_index) = ...
            force_saturated;

        % Do not integrate after the last sample.
        if k == number_of_steps
            break;
        end

        % Hold the measurement errors constant throughout
        % this 0.01-second controller interval.
        controller_k = @(t_local, z_local, par_local) ...
            fixed_gain_error_controller( ...
                z_local, ...
                K, ...
                total_angle_error, ...
                total_gyro_error, ...
                use_force_limit, ...
                force_limit_N ...
            );

        % Fixed-step RK4 integration.
        z = rk4_step( ...
            current_time, ...
            z, ...
            dt, ...
            par, ...
            controller_k ...
        );

        % Stop if the numerical state becomes invalid.
        if any(~isfinite(z))

            simulation_failed(case_index) = true;

            warning( ...
                "Simulation case %d failed at t = %.3f s.", ...
                case_index, ...
                current_time ...
            );

            break;
        end

        z_all(k+1,:,case_index) = z';
    end
end

%% 11. Create plain-text legend labels

colors = lines(number_of_cases);

legend_text = strings(number_of_cases,1);

for case_index = 1:number_of_cases

    legend_text(case_index) = sprintf( ...
        "static = %.2f deg, dynamic limit = %.2f deg", ...
        static_angle_bias_deg_values(case_index), ...
        dynamic_angle_limit_deg_values(case_index) ...
    );
end

%% 12. Plot true system states

figure( ...
    "Name", ...
    "Static and Dynamic IMU Errors", ...
    "Color", ...
    "w" ...
);

subplot(3,1,1);
hold on;

for case_index = 1:number_of_cases

    plot( ...
        t_out, ...
        z_all(:,1,case_index)*180/pi, ...
        "Color", ...
        colors(case_index,:), ...
        "LineWidth", ...
        1.4 ...
    );
end

yline(0, "k--");

ylabel("True theta (deg)");

title( ...
    "True Lean Angle", ...
    "Interpreter", ...
    "none" ...
);

legend( ...
    legend_text, ...
    "Location", ...
    "best", ...
    "Interpreter", ...
    "none" ...
);

grid on;
box on;

subplot(3,1,2);
hold on;

for case_index = 1:number_of_cases

    plot( ...
        t_out, ...
        z_all(:,3,case_index), ...
        "Color", ...
        colors(case_index,:), ...
        "LineWidth", ...
        1.4 ...
    );
end

yline(0, "k--");

ylabel("True r (m)");

title( ...
    "Rod Position", ...
    "Interpreter", ...
    "none" ...
);

grid on;
box on;

subplot(3,1,3);
hold on;

for case_index = 1:number_of_cases

    plot( ...
        t_out, ...
        F_all(:,case_index), ...
        "Color", ...
        colors(case_index,:), ...
        "LineWidth", ...
        1.0 ...
    );
end

if use_force_limit

    yline( ...
        force_limit_N, ...
        "k--", ...
        "Positive force limit", ...
        "Interpreter", ...
        "none" ...
    );

    yline( ...
        -force_limit_N, ...
        "k--", ...
        "Negative force limit", ...
        "Interpreter", ...
        "none" ...
    );
end

xlabel("Time (s)");
ylabel("Force F (N)");

title( ...
    "Applied Controller Force", ...
    "Interpreter", ...
    "none" ...
);

grid on;
box on;

%% 13. Inspect the nominal BNO085 case

% The last case uses the full nominal BNO085 errors.
selected_case = number_of_cases;

figure( ...
    "Name", ...
    "Nominal BNO085 Measurement Errors", ...
    "Color", ...
    "w" ...
);

subplot(3,1,1);

plot( ...
    t_out, ...
    z_all(:,1,selected_case)*180/pi, ...
    "b", ...
    "LineWidth", ...
    1.8 ...
);

hold on;

plot( ...
    t_out, ...
    theta_measured_all(:,selected_case)*180/pi, ...
    "Color", ...
    [0.85, 0.25, 0.20], ...
    "LineWidth", ...
    1.0 ...
);

yline(0, "k--");

ylabel("Theta (deg)");

title( ...
    "True and Measured Lean Angle", ...
    "Interpreter", ...
    "none" ...
);

legend( ...
    "True theta", ...
    "Measured theta", ...
    "Location", ...
    "best", ...
    "Interpreter", ...
    "none" ...
);

grid on;
box on;

subplot(3,1,2);

plot( ...
    t_out, ...
    static_angle_error_all(:,selected_case)*180/pi, ...
    "k--", ...
    "LineWidth", ...
    1.5 ...
);

hold on;

plot( ...
    t_out, ...
    dynamic_angle_error_all(:,selected_case)*180/pi, ...
    "b", ...
    "LineWidth", ...
    1.0 ...
);

plot( ...
    t_out, ...
    ( ...
        static_angle_error_all(:,selected_case) + ...
        dynamic_angle_error_all(:,selected_case) ...
    )*180/pi, ...
    "r", ...
    "LineWidth", ...
    1.2 ...
);

ylabel("Angle error (deg)");

title( ...
    "Static and Dynamic Angle Errors", ...
    "Interpreter", ...
    "none" ...
);

legend( ...
    "Static angle bias", ...
    "Dynamic angle error", ...
    "Total angle error", ...
    "Location", ...
    "best", ...
    "Interpreter", ...
    "none" ...
);

grid on;
box on;

subplot(3,1,3);

plot( ...
    t_out, ...
    dynamic_gyro_error_all(:,selected_case)*180/pi, ...
    "Color", ...
    [0.50, 0.20, 0.75], ...
    "LineWidth", ...
    1.0 ...
);

yline(0, "k--");

xlabel("Time (s)");
ylabel("Gyro error (deg/s)");

title( ...
    "Dynamic Gyroscope Error", ...
    "Interpreter", ...
    "none" ...
);

grid on;
box on;

%% 14. Plot requested and applied force

figure( ...
    "Name", ...
    "Controller Force with BNO085 Errors", ...
    "Color", ...
    "w" ...
);

plot( ...
    t_out, ...
    F_unlimited_all(:,selected_case), ...
    "Color", ...
    [0.55, 0.55, 0.55], ...
    "LineWidth", ...
    0.8 ...
);

hold on;

plot( ...
    t_out, ...
    F_all(:,selected_case), ...
    "r", ...
    "LineWidth", ...
    1.2 ...
);

if use_force_limit

    yline( ...
        force_limit_N, ...
        "k--", ...
        "Force limit", ...
        "Interpreter", ...
        "none" ...
    );

    yline( ...
        -force_limit_N, ...
        "k--" ...
    );
end

xlabel("Time (s)");
ylabel("Force F (N)");

title( ...
    "Unlimited and Applied Controller Force", ...
    "Interpreter", ...
    "none" ...
);

legend( ...
    "Unlimited force request", ...
    "Applied force", ...
    "Location", ...
    "best", ...
    "Interpreter", ...
    "none" ...
);

grid on;
box on;

%% 15. Print numerical results

fprintf("\n");
fprintf("Static and dynamic IMU error simulation results:\n");
fprintf("\n");

fprintf( ...
    "%10s %14s %16s %14s %14s %14s %14s\n", ...
    "scale", ...
    "static", ...
    "dynamic limit", ...
    "gyro limit", ...
    "max|theta|", ...
    "max|r|", ...
    "saturation" ...
);

fprintf( ...
    "%10s %14s %16s %14s %14s %14s %14s\n", ...
    "", ...
    "(deg)", ...
    "(deg)", ...
    "(deg/s)", ...
    "(deg)", ...
    "(m)", ...
    "(percent)" ...
);

for case_index = 1:number_of_cases

    valid_theta = z_all(:,1,case_index);
    valid_theta = valid_theta(isfinite(valid_theta));

    valid_r = z_all(:,3,case_index);
    valid_r = valid_r(isfinite(valid_r));

    if isempty(valid_theta)
        max_theta_deg = NaN;
    else
        max_theta_deg = ...
            max(abs(valid_theta))*180/pi;
    end

    if isempty(valid_r)
        max_r_m = NaN;
    else
        max_r_m = max(abs(valid_r));
    end

    saturation_percentage = ...
        100*mean(force_saturated_all(:,case_index));

    fprintf( ...
        "%10.2f %14.3f %16.3f %14.3f " + ...
        "%14.4f %14.4f %13.2f%%\n", ...
        error_scale_values(case_index), ...
        static_angle_bias_deg_values(case_index), ...
        dynamic_angle_limit_deg_values(case_index), ...
        dynamic_gyro_limit_degps_values(case_index), ...
        max_theta_deg, ...
        max_r_m, ...
        saturation_percentage ...
    );
end

fprintf("\n");

if any(simulation_failed)
    fprintf("Numerically failed cases:\n");
    disp(find(simulation_failed)');
else
    fprintf("No numerical integration failures occurred.\n");
end

%% Local functions

function F_command = fixed_gain_error_controller( ...
    z_true, ...
    K, ...
    total_angle_error, ...
    total_gyro_error, ...
    use_force_limit, ...
    force_limit_N ...
)

    z_measured = [
        z_true(1) + total_angle_error;
        z_true(2) + total_gyro_error;
        z_true(3);
        z_true(4)
    ];

    F_command = -K*z_measured;

    if use_force_limit

        F_command = max( ...
            -force_limit_N, ...
            min(force_limit_N, F_command) ...
        );
    end
end

function z_next = rk4_step( ...
    t, ...
    z, ...
    dt, ...
    par, ...
    controller ...
)

    k1 = LatModel_SignCorrection( ...
        t, ...
        z, ...
        par, ...
        controller ...
    );

    k2 = LatModel_SignCorrection( ...
        t + dt/2, ...
        z + dt*k1/2, ...
        par, ...
        controller ...
    );

    k3 = LatModel_SignCorrection( ...
        t + dt/2, ...
        z + dt*k2/2, ...
        par, ...
        controller ...
    );

    k4 = LatModel_SignCorrection( ...
        t + dt, ...
        z + dt*k3, ...
        par, ...
        controller ...
    );

    z_next = z + ...
        dt*(k1 + 2*k2 + 2*k3 + k4)/6;
end