clear;
clc;
close all;

addpath('param/', 'model/');
par = LatParam();

%% Settings

force_limit = 27.6;
rod_limit = 0.10;
fall_limit = 27*pi/180;

rng(1);

N = 10000;

gain_min = [-900, 150, -150, 10];
gain_max = [-150, 1000, -5, 200];

K_samples = gain_min ...
    + rand(N, 4).*(gain_max - gain_min);

nonlinear_stable_idx = false(N, 1);
force_valid_idx = false(N, 1);
rod_valid_idx = false(N, 1);
simulation_failed_idx = false(N, 1);

max_theta_record = nan(N, 1);
final_theta_record = nan(N, 1);
max_r_record = nan(N, 1);
max_force_record = nan(N, 1);

%% Monte Carlo simulation

z0 = [
    0.1*pi/180;
    0;
    0;
    0
];

tspan = [0, 15];

ode_options = odeset( ...
    'Events', @(t, z) fallDetector(t, z, fall_limit), ...
    'RelTol', 1e-7, ...
    'AbsTol', 1e-9 ...
);

for i = 1:N

    K = K_samples(i, :);

    controller = @(t, z, par) PDController( ...
        z, K, par.R ...
    );

    try
        [t_out, z_out] = ode45( ...
            @(t, z) LatModelAppell( ...
                t, z, par, controller ...
            ), ...
            tspan, ...
            z0, ...
            ode_options ...
        );

        if isempty(z_out) || any(~isfinite(z_out), 'all')
            simulation_failed_idx(i) = true;
            continue;
        end

        x_out = modelToControllerState(z_out, par.R);

        theta_out = x_out(:, 1);
        r_out = x_out(:, 2);

        F_out = -(x_out*K.');

        max_theta = max(abs(theta_out));
        final_theta = abs(theta_out(end));
        max_r = max(abs(r_out));
        max_force = max(abs(F_out));

        simulation_completed = ...
            t_out(end) >= tspan(end) - 1e-6;

        theta_valid = ...
            simulation_completed ...
            && max_theta < 20*pi/180 ...
            && final_theta < 5*pi/180;

        force_valid = ...
            theta_valid ...
            && max_force <= force_limit + 1e-9;

        rod_valid = ...
            theta_valid ...
            && max_r <= rod_limit + 1e-9;

        nonlinear_stable_idx(i) = theta_valid;
        force_valid_idx(i) = force_valid;
        rod_valid_idx(i) = rod_valid;

        max_theta_record(i) = max_theta;
        final_theta_record(i) = final_theta;
        max_r_record(i) = max_r;
        max_force_record(i) = max_force;

    catch
        simulation_failed_idx(i) = true;
    end

    if mod(i, 100) == 0 || i == N
        fprintf('Monte Carlo progress: %d / %d\n', i, N);
    end
end

%% Summary

fprintf('\nMonte Carlo summary\n');

fprintf('Total samples:          %d\n', N);

fprintf('Simulation failed:      %d\n', ...
    sum(simulation_failed_idx));

fprintf('Nonlinear stable:       %d\n', ...
    sum(nonlinear_stable_idx));

fprintf('Force-limit valid:      %d\n', ...
    sum(force_valid_idx));

fprintf('Rod-limit valid:        %d\n', ...
    sum(rod_valid_idx));

fprintf('Both limits valid:      %d\n', ...
    sum(force_valid_idx & rod_valid_idx));

%% Figure 1: force limit

plotGainConstraint( ...
    K_samples, ...
    nonlinear_stable_idx, ...
    force_valid_idx, ...
    'Force Limit Monte Carlo', ...
    'Force valid: max |F| <= 27.6 N' ...
);

%% Figure 2: rod limit

plotGainConstraint( ...
    K_samples, ...
    nonlinear_stable_idx, ...
    rod_valid_idx, ...
    'Rod Limit Monte Carlo', ...
    'Rod valid: max |r| <= 10 cm' ...
);

%% Local functions

function F = PDController(z, K, R)

    theta = z(1);
    theta_dot = z(2);
    r = z(3);
    r_dot = z(4);

    sigma1 = theta_dot;
    sigma2 = r_dot - R*theta_dot;

    x = [theta; r; sigma1; sigma2];

    F = -K*x;
end

function x = modelToControllerState(z, R)

    theta = z(:, 1);
    theta_dot = z(:, 2);
    r = z(:, 3);
    r_dot = z(:, 4);

    sigma1 = theta_dot;
    sigma2 = r_dot - R*theta_dot;

    x = [theta, r, sigma1, sigma2];
end

function [value, isterminal, direction] = ...
    fallDetector(~, z, fall_limit)

    value = fall_limit - abs(z(1));
    isterminal = 1;
    direction = 0;
end

function plotGainConstraint( ...
    K_samples, ...
    nonlinear_idx, ...
    valid_idx, ...
    figure_name, ...
    valid_name)

    K_theta = K_samples(:, 1);
    K_r = K_samples(:, 2);
    K_sigma1 = K_samples(:, 3);
    K_sigma2 = K_samples(:, 4);

    figure( ...
        'Name', figure_name, ...
        'Position', [100, 100, 1250, 520] ...
    );

    subplot(1, 2, 1);
    hold on;

    scatter( ...
        K_theta, ...
        K_r, ...
        8, ...
        [0.75, 0.75, 0.75], ...
        'filled', ...
        'MarkerFaceAlpha', 0.25, ...
        'DisplayName', 'All samples' ...
    );

    if any(nonlinear_idx)
        scatter( ...
            K_theta(nonlinear_idx), ...
            K_r(nonlinear_idx), ...
            25, ...
            'b', ...
            'filled', ...
            'DisplayName', 'Nonlinear stable' ...
        );
    end

    if any(valid_idx)
        scatter( ...
            K_theta(valid_idx), ...
            K_r(valid_idx), ...
            45, ...
            'g', ...
            'filled', ...
            'DisplayName', valid_name ...
        );
    end

    xlabel('$K_\theta$', 'Interpreter', 'latex');
    ylabel('$K_r$', 'Interpreter', 'latex');
    title('Position Gains');

    legend('Location', 'best');
    grid on;
    box on;
    hold off;

    subplot(1, 2, 2);
    hold on;

    scatter( ...
        K_sigma1, ...
        K_sigma2, ...
        8, ...
        [0.75, 0.75, 0.75], ...
        'filled', ...
        'MarkerFaceAlpha', 0.25, ...
        'DisplayName', 'All samples' ...
    );

    if any(nonlinear_idx)
        scatter( ...
            K_sigma1(nonlinear_idx), ...
            K_sigma2(nonlinear_idx), ...
            25, ...
            'b', ...
            'filled', ...
            'DisplayName', 'Nonlinear stable' ...
        );
    end

    if any(valid_idx)
        scatter( ...
            K_sigma1(valid_idx), ...
            K_sigma2(valid_idx), ...
            45, ...
            'g', ...
            'filled', ...
            'DisplayName', valid_name ...
        );
    end

    xlabel('$K_{\sigma_1}$', 'Interpreter', 'latex');
    ylabel('$K_{\sigma_2}$', 'Interpreter', 'latex');
    title('Generalized-Speed Gains');

    legend('Location', 'best');
    grid on;
    box on;
    hold off;

    sgtitle(figure_name);
end