clear;
clc;
close all;

addpath('param/', 'model/');
par = LatParam();

%% Settings

force_limit = 27.6;
rod_limit = 0.10;
fall_limit = 27*pi/180;

rng(1);

N = 10000;

gain_min = [-900, 150, -150, 10];
gain_max = [-150, 1000, -5, 200];

K_samples = gain_min ...
    + rand(N, 4).*(gain_max - gain_min);

nonlinear_stable_idx = false(N, 1);
force_valid_idx = false(N, 1);
rod_valid_idx = false(N, 1);
simulation_failed_idx = false(N, 1);

max_theta_record = nan(N, 1);
final_theta_record = nan(N, 1);
max_r_record = nan(N, 1);
max_force_record = nan(N, 1);

%% Closed-loop nonzero-equilibrium contours
%
% Static mechanical equilibrium:
%
% F_eq = m*g*sin(theta_eq)
%
% r_eq = equilibrium_factor*tan(theta_eq)
%
% Linear feedback at equilibrium:
%
% F_eq = -K_theta*theta_eq - K_r*r_eq
%
% Therefore:
%
% K_theta*theta_eq
% + K_r*equilibrium_factor*tan(theta_eq)
% + m*g*sin(theta_eq) = 0
%
% theta_eq = 0 is always an equilibrium.
% The calculation below finds the positive nonzero equilibrium.

equilibrium_data = buildEquilibriumContourData( ...
    gain_min, ...
    gain_max, ...
    par, ...
    fall_limit, ...
    rod_limit ...
);

% Evaluate the positive nonzero equilibrium for every sampled gain set.
% These values are used below to identify the feasible gain set that
% permits the largest equilibrium angle.

theta_search_max = min( ...
    fall_limit, ...
    pi/2 - 1e-5 ...
);

theta_equilibrium_record = ...
    solvePositiveNonzeroEquilibrium( ...
        K_samples(:, 1), ...
        K_samples(:, 2), ...
        equilibrium_data.factor, ...
        par.m_rod, ...
        par.g, ...
        theta_search_max ...
    );

r_equilibrium_record = ...
    equilibrium_data.factor ...
    .* tan(theta_equilibrium_record);

force_equilibrium_record = ...
    par.m_rod*par.g ...
    .* sin(theta_equilibrium_record);

fprintf('\nClosed-loop equilibrium information\n');

fprintf( ...
    'Equilibrium factor:        %.6f m\n', ...
    equilibrium_data.factor ...
);

fprintf( ...
    'Rod-limit angle:           %.6f deg\n', ...
    equilibrium_data.theta_rod_limit_deg ...
);

%% Monte Carlo simulation

z0 = [
    0.9*pi/180;
    0;
    0;
    0
];

tspan = [0, 15];

ode_options = odeset( ...
    'Events', @(t, z) fallDetector(t, z, fall_limit), ...
    'RelTol', 1e-7, ...
    'AbsTol', 1e-9 ...
);

for i = 1:N

    K = K_samples(i, :);

    controller = @(t, z, par) PDController( ...
        z, ...
        K, ...
        par.R ...
    );

    try
        [t_out, z_out] = ode45( ...
            @(t, z) LatModelAppell( ...
                t, ...
                z, ...
                par, ...
                controller ...
            ), ...
            tspan, ...
            z0, ...
            ode_options ...
        );

        if isempty(z_out) || any(~isfinite(z_out), 'all')
            simulation_failed_idx(i) = true;
            continue;
        end

        x_out = modelToControllerState( ...
            z_out, ...
            par.R ...
        );

        theta_out = x_out(:, 1);
        r_out = x_out(:, 2);

        F_out = -(x_out*K.');

        max_theta = max(abs(theta_out));
        final_theta = abs(theta_out(end));
        max_r = max(abs(r_out));
        max_force = max(abs(F_out));

        simulation_completed = ...
            t_out(end) >= tspan(end) - 1e-6;

        theta_valid = ...
            simulation_completed ...
            && max_theta < 20*pi/180 ...
            && final_theta < 5*pi/180;

        force_valid = ...
            theta_valid ...
            && max_force <= force_limit + 1e-9;

        rod_valid = ...
            theta_valid ...
            && max_r <= rod_limit + 1e-9;

        nonlinear_stable_idx(i) = theta_valid;
        force_valid_idx(i) = force_valid;
        rod_valid_idx(i) = rod_valid;

        max_theta_record(i) = max_theta;
        final_theta_record(i) = final_theta;
        max_r_record(i) = max_r;
        max_force_record(i) = max_force;

    catch
        simulation_failed_idx(i) = true;
    end

    if mod(i, 100) == 0 || i == N
        fprintf( ...
            'Monte Carlo progress: %d / %d\n', ...
            i, ...
            N ...
        );
    end
end

%% Summary

fprintf('\nMonte Carlo summary\n');

fprintf( ...
    'Total samples:          %d\n', ...
    N ...
);

fprintf( ...
    'Simulation failed:      %d\n', ...
    sum(simulation_failed_idx) ...
);

fprintf( ...
    'Nonlinear stable:       %d\n', ...
    sum(nonlinear_stable_idx) ...
);

fprintf( ...
    'Force-limit valid:      %d\n', ...
    sum(force_valid_idx) ...
);

fprintf( ...
    'Rod-limit valid:        %d\n', ...
    sum(rod_valid_idx) ...
);

fprintf( ...
    'Both limits valid:      %d\n', ...
    sum(force_valid_idx & rod_valid_idx) ...
);

%% Best available nonzero equilibrium

% Selection priority:
%   1. all simulated and equilibrium limits satisfied;
%   2. force-limit-valid and equilibrium-force-valid;
%   3. nonlinear stable;
%   4. any sampled gain set with a positive nonzero equilibrium.
%
% This fallback hierarchy guarantees that the best available gain set is
% still printed when no sample satisfies the rod limit. The printed
% selection class states clearly which constraints were retained.

equilibrium_force_valid_idx = ...
    abs(force_equilibrium_record) ...
    <= force_limit + 1e-9;

equilibrium_rod_valid_idx = ...
    abs(r_equilibrium_record) ...
    <= rod_limit + 1e-9;

strict_candidate_idx = ...
    force_valid_idx ...
    & rod_valid_idx ...
    & isfinite(theta_equilibrium_record) ...
    & equilibrium_force_valid_idx ...
    & equilibrium_rod_valid_idx;

force_candidate_idx = ...
    force_valid_idx ...
    & isfinite(theta_equilibrium_record) ...
    & equilibrium_force_valid_idx;

stable_candidate_idx = ...
    nonlinear_stable_idx ...
    & isfinite(theta_equilibrium_record);

equilibrium_candidate_idx = ...
    isfinite(theta_equilibrium_record);

if any(strict_candidate_idx)

    best_candidate_idx = strict_candidate_idx;
    selection_name = ...
        'all force and rod limits satisfied';

elseif any(force_candidate_idx)

    best_candidate_idx = force_candidate_idx;
    selection_name = ...
        'force-limit valid; rod limit relaxed';

elseif any(stable_candidate_idx)

    best_candidate_idx = stable_candidate_idx;
    selection_name = ...
        'nonlinear stable; force and rod limits relaxed';

elseif any(equilibrium_candidate_idx)

    best_candidate_idx = equilibrium_candidate_idx;
    selection_name = ...
        'nonzero equilibrium exists; simulation limits relaxed';

else

    best_candidate_idx = false(N, 1);
    selection_name = ...
        'no positive nonzero equilibrium found';

end

fprintf('\nBest available nonzero equilibrium\n');

fprintf( ...
    'Selection class:         %s\n', ...
    selection_name ...
);

fprintf( ...
    'Candidates in class:     %d\n', ...
    sum(best_candidate_idx) ...
);

if any(best_candidate_idx)

    candidate_indices = find(best_candidate_idx);

    [best_theta_eq, local_best_idx] = max( ...
        theta_equilibrium_record(best_candidate_idx) ...
    );

    best_sample_idx = ...
        candidate_indices(local_best_idx);

    best_K = K_samples(best_sample_idx, :);

    % Convert the generalized-speed gains to the ordinary derivative
    % gains because sigma1 = theta_dot and
    % sigma2 = r_dot - R*theta_dot:
    %
    % K_dtheta = K_sigma1 - R*K_sigma2,
    % K_dr     = K_sigma2.
    best_K_dtheta = ...
        best_K(3) - par.R*best_K(4);
    best_K_dr = best_K(4);

    best_r_eq = r_equilibrium_record(best_sample_idx);
    best_force_eq = ...
        force_equilibrium_record(best_sample_idx);

    % This residual checks the static feedback balance
    % F_eq = -K_theta*theta_eq - K_r*r_eq.
    best_equilibrium_residual = ...
        -best_K(1)*best_theta_eq ...
        -best_K(2)*best_r_eq ...
        -best_force_eq;

    fprintf( ...
        'Sample index:           %d\n', ...
        best_sample_idx ...
    );

    fprintf( ...
        'K_theta:                %.9g\n', ...
        best_K(1) ...
    );

    fprintf( ...
        'K_r:                    %.9g\n', ...
        best_K(2) ...
    );

    fprintf( ...
        'K_dtheta:               %.9g\n', ...
        best_K_dtheta ...
    );

    fprintf( ...
        'K_dr:                   %.9g\n', ...
        best_K_dr ...
    );

    fprintf( ...
        'Equilibrium theta:      +/- %.9f deg\n', ...
        best_theta_eq*180/pi ...
    );

    fprintf( ...
        ['Equilibrium r:          +/- %.9f m ' ...
        '(%.6f cm)\n'], ...
        best_r_eq, ...
        100*best_r_eq ...
    );

    fprintf( ...
        'Equilibrium |F|:        %.9f N\n', ...
        abs(best_force_eq) ...
    );

    fprintf( ...
        'Equilibrium residual:   %.3e N\n', ...
        best_equilibrium_residual ...
    );

    fprintf( ...
        'Simulated max |theta|:  %.9f deg\n', ...
        max_theta_record(best_sample_idx)*180/pi ...
    );

    fprintf( ...
        'Simulated final theta:  %.9f deg\n', ...
        final_theta_record(best_sample_idx)*180/pi ...
    );

    fprintf( ...
        'Simulated max |r|:      %.6f cm\n', ...
        100*max_r_record(best_sample_idx) ...
    );

    fprintf( ...
        'Simulated max |F|:      %.9f N\n', ...
        max_force_record(best_sample_idx) ...
    );

else

    best_sample_idx = [];

    fprintf( ...
        ['No sampled gain set has a positive nonzero ' ...
        'equilibrium inside the search-angle range.\n'] ...
    );

end

%% Figure 1: force limit

plotGainConstraint( ...
    K_samples, ...
    nonlinear_stable_idx, ...
    force_valid_idx, ...
    'Force Limit Monte Carlo', ...
    'Force valid: max |F| <= 27.6 N', ...
    equilibrium_data ...
);

%% Figure 2: rod limit

plotGainConstraint( ...
    K_samples, ...
    nonlinear_stable_idx, ...
    rod_valid_idx, ...
    'Rod Limit Monte Carlo', ...
    'Rod valid: max |r| <= 10 cm', ...
    equilibrium_data ...
);

%% Local functions

function F = PDController(z, K, R)

    theta = z(1);
    theta_dot = z(2);
    r = z(3);
    r_dot = z(4);

    sigma1 = theta_dot;
    sigma2 = r_dot - R*theta_dot;

    x = [
        theta;
        r;
        sigma1;
        sigma2
    ];

    F = -K*x;
end

function x = modelToControllerState(z, R)

    theta = z(:, 1);
    theta_dot = z(:, 2);
    r = z(:, 3);
    r_dot = z(:, 4);

    sigma1 = theta_dot;
    sigma2 = r_dot - R*theta_dot;

    x = [
        theta, ...
        r, ...
        sigma1, ...
        sigma2
    ];
end

function [value, isterminal, direction] = ...
    fallDetector(~, z, fall_limit)

    value = fall_limit - abs(z(1));
    isterminal = 1;
    direction = 0;
end

function equilibrium_data = ...
    buildEquilibriumContourData( ...
        gain_min, ...
        gain_max, ...
        par, ...
        fall_limit, ...
        rod_limit ...
    )

    m = par.m_rod;
    g = par.g;
    R = par.R;
    G = par.G;

    equilibrium_factor = ...
        (G + m*g*R)/(m*g);

    grid_size = 300;

    K_theta_values = linspace( ...
        gain_min(1), ...
        gain_max(1), ...
        grid_size ...
    );

    K_r_values = linspace( ...
        gain_min(2), ...
        gain_max(2), ...
        grid_size ...
    );

    [K_theta_grid, K_r_grid] = meshgrid( ...
        K_theta_values, ...
        K_r_values ...
    );

    theta_search_max = min( ...
        fall_limit, ...
        pi/2 - 1e-5 ...
    );

    theta_eq_grid = ...
        solvePositiveNonzeroEquilibrium( ...
            K_theta_grid, ...
            K_r_grid, ...
            equilibrium_factor, ...
            m, ...
            g, ...
            theta_search_max ...
        );

    theta_eq_grid_deg = ...
        theta_eq_grid*180/pi;

    theta_rod_limit = atan( ...
        rod_limit/equilibrium_factor ...
    );

    theta_rod_limit_deg = ...
        theta_rod_limit*180/pi;

    % Boundary where the nonzero equilibrium branch
    % emerges from theta = 0:
    %
    % K_theta + equilibrium_factor*K_r + m*g = 0.

    K_r_boundary = linspace( ...
        gain_min(2), ...
        gain_max(2), ...
        600 ...
    );

    K_theta_boundary = ...
        -equilibrium_factor*K_r_boundary ...
        -m*g;

    boundary_valid = ...
        K_theta_boundary >= gain_min(1) ...
        & K_theta_boundary <= gain_max(1);

    equilibrium_data.K_theta_grid = ...
        K_theta_grid;

    equilibrium_data.K_r_grid = ...
        K_r_grid;

    equilibrium_data.theta_eq_grid_deg = ...
        theta_eq_grid_deg;

    equilibrium_data.factor = ...
        equilibrium_factor;

    equilibrium_data.theta_rod_limit_deg = ...
        theta_rod_limit_deg;

    equilibrium_data.rod_limit = ...
        rod_limit;

    equilibrium_data.K_r_boundary = ...
        K_r_boundary(boundary_valid);

    equilibrium_data.K_theta_boundary = ...
        K_theta_boundary(boundary_valid);
end

function theta_eq = ...
    solvePositiveNonzeroEquilibrium( ...
        K_theta, ...
        K_r, ...
        equilibrium_factor, ...
        m, ...
        g, ...
        theta_max ...
    )

    theta_eq = nan(size(K_theta));

    % Derivative of the equilibrium equation at theta = 0:
    %
    % q'(0) = K_theta
    %       + equilibrium_factor*K_r
    %       + m*g.

    origin_slope = ...
        K_theta ...
        + equilibrium_factor*K_r ...
        + m*g;

    q_at_max = ...
        K_theta*theta_max ...
        + K_r*equilibrium_factor*tan(theta_max) ...
        + m*g*sin(theta_max);

    % A positive nonzero equilibrium lies inside the
    % search interval when the equation initially decreases
    % from zero and becomes nonnegative before theta_max.

    valid_idx = ...
        origin_slope < 0 ...
        & q_at_max >= 0;

    if ~any(valid_idx, 'all')
        return;
    end

    theta_lower = zeros(size(K_theta));

    theta_upper = ...
        theta_max*ones(size(K_theta));

    % Vectorized bisection.
    for iteration = 1:60

        theta_mid = ...
            0.5*(theta_lower + theta_upper);

        q_mid = ...
            K_theta.*theta_mid ...
            + K_r.*equilibrium_factor.*tan(theta_mid) ...
            + m*g*sin(theta_mid);

        lower_update = ...
            valid_idx ...
            & q_mid <= 0;

        upper_update = ...
            valid_idx ...
            & q_mid > 0;

        theta_lower(lower_update) = ...
            theta_mid(lower_update);

        theta_upper(upper_update) = ...
            theta_mid(upper_update);
    end

    theta_eq(valid_idx) = ...
        0.5*( ...
            theta_lower(valid_idx) ...
            + theta_upper(valid_idx) ...
        );
end

function plotGainConstraint( ...
    K_samples, ...
    nonlinear_idx, ...
    valid_idx, ...
    figure_name, ...
    valid_name, ...
    equilibrium_data ...
)

    K_theta = K_samples(:, 1);
    K_r = K_samples(:, 2);
    K_sigma1 = K_samples(:, 3);
    K_sigma2 = K_samples(:, 4);

    % Display only part of the gray random background.
    % All samples are still used in the calculations.
    background_idx = 1:4:size(K_samples, 1);

    fig = figure( ...
        'Name', figure_name, ...
        'Color', 'w', ...
        'Position', [60, 80, 1650, 650] ...
    );

    layout = tiledlayout( ...
        fig, ...
        1, ...
        2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact' ...
    );

    title( ...
        layout, ...
        figure_name, ...
        'FontSize', 16, ...
        'FontWeight', 'bold' ...
    );

    %% Position-gain subplot

    ax1 = nexttile(layout, 1);
    hold(ax1, 'on');

    % Draw the equilibrium-angle background first.
    [h_rod_limit, h_equilibrium_boundary] = ...
        plotEquilibriumContours( ...
            equilibrium_data, ...
            ax1 ...
        );

    legend_handles = gobjects(0);

    h_all = scatter( ...
        ax1, ...
        K_theta(background_idx), ...
        K_r(background_idx), ...
        8, ...
        [0.25, 0.25, 0.25], ...
        'filled', ...
        'MarkerFaceAlpha', 0.10, ...
        'MarkerEdgeAlpha', 0.05, ...
        'DisplayName', ...
        'Random samples (25% shown)' ...
    );

    legend_handles(end + 1) = h_all;

    if any(nonlinear_idx)

        h_stable = scatter( ...
            ax1, ...
            K_theta(nonlinear_idx), ...
            K_r(nonlinear_idx), ...
            38, ...
            [0.00, 0.30, 0.95], ...
            'filled', ...
            'MarkerEdgeColor', 'w', ...
            'LineWidth', 0.5, ...
            'DisplayName', ...
            'Nonlinear stable' ...
        );

        legend_handles(end + 1) = h_stable;
    end

    if any(valid_idx)

        h_valid = scatter( ...
            ax1, ...
            K_theta(valid_idx), ...
            K_r(valid_idx), ...
            75, ...
            [0.00, 0.80, 0.20], ...
            'filled', ...
            'MarkerEdgeColor', [0.00, 0.30, 0.05], ...
            'LineWidth', 1.0, ...
            'DisplayName', ...
            valid_name ...
        );

        legend_handles(end + 1) = h_valid;
    end

    if isgraphics(h_rod_limit)
        legend_handles(end + 1) = ...
            h_rod_limit;
    end

    if isgraphics(h_equilibrium_boundary)
        legend_handles(end + 1) = ...
            h_equilibrium_boundary;
    end

    xlabel( ...
        ax1, ...
        '$K_\theta$', ...
        'Interpreter', 'latex', ...
        'FontSize', 14 ...
    );

    ylabel( ...
        ax1, ...
        '$K_r$', ...
        'Interpreter', 'latex', ...
        'FontSize', 14 ...
    );

    title( ...
        ax1, ...
        'Position Gains', ...
        'FontSize', 14 ...
    );

    xlim(ax1, [min(K_theta), max(K_theta)]);
    ylim(ax1, [min(K_r), max(K_r)]);

    set( ...
        ax1, ...
        'FontSize', 12, ...
        'LineWidth', 1.0, ...
        'Layer', 'top', ...
        'TickDir', 'out', ...
        'GridAlpha', 0.18 ...
    );

    grid(ax1, 'on');
    box(ax1, 'on');

    legend( ...
        ax1, ...
        legend_handles, ...
        'Location', 'southwest', ...
        'FontSize', 9, ...
        'Box', 'on' ...
    );

    hold(ax1, 'off');

    %% Generalized-speed-gain subplot

    ax2 = nexttile(layout, 2);
    hold(ax2, 'on');

    legend_handles_2 = gobjects(0);

    h_all_2 = scatter( ...
        ax2, ...
        K_sigma1(background_idx), ...
        K_sigma2(background_idx), ...
        8, ...
        [0.35, 0.35, 0.35], ...
        'filled', ...
        'MarkerFaceAlpha', 0.08, ...
        'MarkerEdgeAlpha', 0.04, ...
        'DisplayName', ...
        'Random samples (25% shown)' ...
    );

    legend_handles_2(end + 1) = h_all_2;

    if any(nonlinear_idx)

        h_stable_2 = scatter( ...
            ax2, ...
            K_sigma1(nonlinear_idx), ...
            K_sigma2(nonlinear_idx), ...
            38, ...
            [0.00, 0.30, 0.95], ...
            'filled', ...
            'MarkerEdgeColor', 'w', ...
            'LineWidth', 0.5, ...
            'DisplayName', ...
            'Nonlinear stable' ...
        );

        legend_handles_2(end + 1) = ...
            h_stable_2;
    end

    if any(valid_idx)

        h_valid_2 = scatter( ...
            ax2, ...
            K_sigma1(valid_idx), ...
            K_sigma2(valid_idx), ...
            75, ...
            [0.00, 0.80, 0.20], ...
            'filled', ...
            'MarkerEdgeColor', [0.00, 0.30, 0.05], ...
            'LineWidth', 1.0, ...
            'DisplayName', ...
            valid_name ...
        );

        legend_handles_2(end + 1) = ...
            h_valid_2;
    end

    xlabel( ...
        ax2, ...
        '$K_{\sigma_1}$', ...
        'Interpreter', 'latex', ...
        'FontSize', 14 ...
    );

    ylabel( ...
        ax2, ...
        '$K_{\sigma_2}$', ...
        'Interpreter', 'latex', ...
        'FontSize', 14 ...
    );

    title( ...
        ax2, ...
        'Generalized-Speed Gains', ...
        'FontSize', 14 ...
    );

    xlim(ax2, [min(K_sigma1), max(K_sigma1)]);
    ylim(ax2, [min(K_sigma2), max(K_sigma2)]);

    set( ...
        ax2, ...
        'FontSize', 12, ...
        'LineWidth', 1.0, ...
        'Layer', 'top', ...
        'TickDir', 'out', ...
        'GridAlpha', 0.18 ...
    );

    grid(ax2, 'on');
    box(ax2, 'on');

    legend( ...
        ax2, ...
        legend_handles_2, ...
        'Location', 'southeast', ...
        'FontSize', 9, ...
        'Box', 'on' ...
    );

    hold(ax2, 'off');
end

function [h_rod_limit, h_boundary] = ...
    plotEquilibriumContours( ...
        equilibrium_data, ...
        ax ...
    )

    K_theta_grid = ...
        equilibrium_data.K_theta_grid;

    K_r_grid = ...
        equilibrium_data.K_r_grid;

    theta_eq_deg = ...
        equilibrium_data.theta_eq_grid_deg;

    h_rod_limit = gobjects(1);
    h_boundary = gobjects(1);

    finite_values = ...
        theta_eq_deg(isfinite(theta_eq_deg));

    if isempty(finite_values)
        return;
    end

    maximum_angle = ...
        ceil(max(finite_values));

    %% Filled equilibrium-angle map

    filled_levels = linspace( ...
        0, ...
        maximum_angle, ...
        35 ...
    );

    contourf( ...
        ax, ...
        K_theta_grid, ...
        K_r_grid, ...
        theta_eq_deg, ...
        filled_levels, ...
        'LineStyle', 'none', ...
        'HandleVisibility', 'off' ...
    );

    % Use a lightened colormap so that scatter points
    % remain visible.
    if exist('turbo', 'file') ...
            || exist('turbo', 'builtin')

        color_map = turbo(256);
    else
        color_map = parula(256);
    end

    color_map = ...
        0.62*color_map ...
        + 0.38*ones(size(color_map));

    colormap(ax, color_map);

    caxis(ax, [0, maximum_angle]);

    color_bar = colorbar(ax);

    color_bar.Label.Interpreter = 'latex';

    color_bar.Label.String = ...
        '$|\theta_{\mathrm{eq}}|$ (deg)';

    color_bar.Label.FontSize = 12;
    color_bar.FontSize = 10;

    %% Unlabelled reference contours

    line_levels = [
        2, ...
        5, ...
        10, ...
        15, ...
        20, ...
        25
    ];

    line_levels = line_levels( ...
        line_levels <= maximum_angle ...
    );

    if ~isempty(line_levels)

        contour( ...
            ax, ...
            K_theta_grid, ...
            K_r_grid, ...
            theta_eq_deg, ...
            line_levels, ...
            'LineColor', [0.18, 0.18, 0.18], ...
            'LineWidth', 0.65, ...
            'HandleVisibility', 'off' ...
        );
    end

    %% Rod-limit equilibrium contour

    rod_angle = ...
        equilibrium_data.theta_rod_limit_deg;

    if rod_angle <= maximum_angle

        % White underlay.
        contour( ...
            ax, ...
            K_theta_grid, ...
            K_r_grid, ...
            theta_eq_deg, ...
            [rod_angle, rod_angle], ...
            'LineColor', 'w', ...
            'LineWidth', 4.0, ...
            'HandleVisibility', 'off' ...
        );

        [~, h_rod_limit] = contour( ...
            ax, ...
            K_theta_grid, ...
            K_r_grid, ...
            theta_eq_deg, ...
            [rod_angle, rod_angle], ...
            '--', ...
            'LineColor', [0.90, 0.10, 0.05], ...
            'LineWidth', 2.4 ...
        );

        h_rod_limit.DisplayName = sprintf( ...
            'Nonzero equilibrium at |r| = %.0f cm', ...
            100*equilibrium_data.rod_limit ...
        );
    end

    %% Boundary where the nonzero branch emerges

    if ~isempty(equilibrium_data.K_theta_boundary)

        % White underlay.
        plot( ...
            ax, ...
            equilibrium_data.K_theta_boundary, ...
            equilibrium_data.K_r_boundary, ...
            '-', ...
            'Color', 'w', ...
            'LineWidth', 4.5, ...
            'HandleVisibility', 'off' ...
        );

        h_boundary = plot( ...
            ax, ...
            equilibrium_data.K_theta_boundary, ...
            equilibrium_data.K_r_boundary, ...
            'k--', ...
            'LineWidth', 2.2, ...
            'DisplayName', ...
            'Nonzero-equilibrium boundary' ...
        );
    end
end
