clear;
clc;
close all;

addpath("param/", "model/");

%% 1. System parameters

par = LatParam();

m = par.m_rod;
R = par.R;
g = par.g;
G = par.G;

equilibrium_factor = ...
    (G + m*g*R)/(m*g);

force_limit = 100000;  % N
rod_limit = 10;        % m

%% 2. Controller settings
%
% e = r-r_eq(theta)
%
% e_dot = r_dot-r_eq_dot(theta)
%
% F = m*g*sin(theta) + k*e + velocity_gain*e_dot
%
% r_eq(theta) = equilibrium_factor*tan(theta)
%
% r_eq_dot(theta)
% = equilibrium_factor*sec(theta)^2*theta_dot

k_values = [
    -200, ...
    -300, ...
    -500, ...
    -800, ...
];  % N/m

velocity_gain = -40;  % N*s/m

num_cases = length(k_values);
case_colors = lines(num_cases);

%% 3. Initial condition
%
% State order:
% z = [theta; theta_dot; r; r_dot]

theta0 = 0.10;  % rad
r0 = 0.00;      % m

z0 = [
    theta0;
    0;
    r0;
    0
];

r_eq_initial = ...
    equilibrium_factor*tan(theta0);

fprintf('Initial condition:\n');
fprintf('  theta0          = %.6f rad\n', theta0);
fprintf('  r0              = %.6f m\n', r0);
fprintf( ...
    '  r_eq(theta0)    = %.6f m\n', ...
    r_eq_initial);
fprintf( ...
    '  initial r error = %.6f m\n\n', ...
    r0-r_eq_initial);

%% 4. Simulation settings

tspan = [0, 15];

ode_options = odeset( ...
    'RelTol', 1e-8, ...
    'AbsTol', 1e-10, ...
    'MaxStep', 0.002);

chunk_duration = 0.02;  % s

%% 5. Allocate results

results = struct( ...
    'k', cell(num_cases, 1), ...
    'velocity_gain', cell(num_cases, 1), ...
    't', cell(num_cases, 1), ...
    'z', cell(num_cases, 1), ...
    'r_eq', cell(num_cases, 1), ...
    'r_eq_dot', cell(num_cases, 1), ...
    'r_error', cell(num_cases, 1), ...
    'r_error_dot', cell(num_cases, 1), ...
    'F', cell(num_cases, 1), ...
    'stopped_early', cell(num_cases, 1), ...
    'stop_message', cell(num_cases, 1));

%% 6. Scan k values

for j = 1:num_cases

    k = k_values(j);

    fprintf( ...
        ['Simulating k = %+7.1f N/m, ', ...
         'velocity gain = %+7.1f N*s/m...\n'], ...
        k, ...
        velocity_gain);

    controller = @(t, z, par) ...
        max( ...
            -force_limit, ...
            min( ...
                force_limit, ...
                par.m_rod*par.g*sin(z(1)) ...
                + k*( ...
                    z(3) ...
                    - equilibrium_factor*tan(z(1)) ...
                ) ...
                + velocity_gain*( ...
                    z(4) ...
                    - equilibrium_factor ...
                    /(cos(z(1))^2)*z(2) ...
                )));

    model_rhs = @(t, z) ...
        LatModel_SignCorrection( ...
            t, z, par, controller);

    t_all = tspan(1);
    z_all = z0(:).';

    t_current = tspan(1);
    z_current = z0(:);

    stopped_early = false;
    stop_message = '';

    while t_current < tspan(end)

        t_segment_end = min( ...
            t_current + chunk_duration, ...
            tspan(end));

        try
            [t_segment, z_segment] = ode45( ...
                model_rhs, ...
                [t_current, t_segment_end], ...
                z_current, ...
                ode_options);

        catch ME
            stopped_early = true;
            stop_message = ME.message;

            fprintf( ...
                ['  Model error at t = %.6f s.\n', ...
                 '  Last valid state was retained.\n', ...
                 '  Error: %s\n'], ...
                t_current, ...
                ME.message);

            break;
        end

        if any(~isfinite(t_segment(:))) || ...
           any(~isfinite(z_segment(:)))

            stopped_early = true;
            stop_message = ...
                'NaN or Inf appeared in the simulation.';

            fprintf( ...
                ['  NaN or Inf detected at ', ...
                 't = %.6f s.\n'], ...
                t_current);

            break;
        end

        if length(t_segment) > 1
            t_all = [
                t_all;
                t_segment(2:end)
            ];

            z_all = [
                z_all;
                z_segment(2:end, :)
            ];
        end

        previous_time = t_current;

        t_current = t_segment(end);
        z_current = z_segment(end, :).';

        time_tolerance = ...
            10*eps(max(1, abs(previous_time)));

        if t_current <= previous_time + time_tolerance
            stopped_early = true;
            stop_message = ...
                'ode45 returned without advancing time.';

            fprintf( ...
                ['  ode45 did not advance past ', ...
                 't = %.6f s.\n'], ...
                t_current);

            break;
        end

        segment_tolerance = ...
            1e-10*max(1, abs(t_segment_end));

        if t_current < ...
                t_segment_end-segment_tolerance

            stopped_early = true;
            stop_message = ...
                ['ode45 returned before reaching ', ...
                 'the requested segment endpoint.'];

            fprintf( ...
                ['  ode45 returned early at ', ...
                 't = %.6f s.\n'], ...
                t_current);

            break;
        end
    end

    %% Process valid data for this k

    t_out = t_all;
    z_out = z_all;

    theta_out = z_out(:, 1);
    theta_dot_out = z_out(:, 2);
    r_out = z_out(:, 3);
    r_dot_out = z_out(:, 4);

    r_eq_out = ...
        equilibrium_factor*tan(theta_out);

    r_eq_dot_out = ...
        equilibrium_factor ...
        ./(cos(theta_out).^2) ...
        .*theta_dot_out;

    r_error_out = ...
        r_out-r_eq_out;

    r_error_dot_out = ...
        r_dot_out-r_eq_dot_out;

    F_out = ...
        m*g*sin(theta_out) ...
        + k*r_error_out ...
        + velocity_gain*r_error_dot_out;

    F_out = max( ...
        -force_limit, ...
        min(force_limit, F_out));

    results(j).k = k;
    results(j).velocity_gain = velocity_gain;
    results(j).t = t_out;
    results(j).z = z_out;
    results(j).r_eq = r_eq_out;
    results(j).r_eq_dot = r_eq_dot_out;
    results(j).r_error = r_error_out;
    results(j).r_error_dot = r_error_dot_out;
    results(j).F = F_out;
    results(j).stopped_early = stopped_early;
    results(j).stop_message = stop_message;

    if stopped_early
        fprintf( ...
            ['  k = %+7.1f N/m stopped early ', ...
             'at t = %.6f s.\n\n'], ...
            k, t_out(end));
    else
        fprintf( ...
            ['  k = %+7.1f N/m successfully ', ...
             'reached t = %.6f s.\n\n'], ...
            k, t_out(end));
    end
end

%% 7. Time-history plots

figure( ...
    'Name', ...
    'Equilibrium-curve PD gain scan', ...
    'Color', 'w');

subplot(5, 1, 1);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).z(:, 1), ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5, ...
        'DisplayName', sprintf( ...
            'k = %+g N/m', ...
            results(j).k));
end

yline( ...
    0, ...
    '--k', ...
    'Upright', ...
    'HandleVisibility', 'off');

ylabel( ...
    '$\theta\;(\mathrm{rad})$', ...
    'Interpreter', 'latex');

title( ...
    sprintf( ...
        ['$F=m_{\\mathrm{rod}}g\\sin\\theta', ...
         '+k e+c\\dot e,\\quad c=%+g$ N s/m'], ...
        velocity_gain), ...
    'Interpreter', 'latex');

legend('Location', 'eastoutside');

hold off;

subplot(5, 1, 2);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).z(:, 3), ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5);
end

ylabel( ...
    '$r\;(\mathrm{m})$', ...
    'Interpreter', 'latex');

hold off;

subplot(5, 1, 3);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).r_error, ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5);
end

yline(0, '--k', 'Equilibrium curve');

ylabel( ...
    '$e=r-r_{\mathrm{eq}}\;(\mathrm{m})$', ...
    'Interpreter', 'latex');

hold off;

subplot(5, 1, 4);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).r_error_dot, ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5);
end

yline(0, '--k');

ylabel( ...
    '$\dot e\;(\mathrm{m/s})$', ...
    'Interpreter', 'latex');

hold off;

subplot(5, 1, 5);
hold on;
grid on;
box on;

for j = 1:num_cases
    plot( ...
        results(j).t, ...
        results(j).F, ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5);
end

xlabel( ...
    '$t\;(\mathrm{s})$', ...
    'Interpreter', 'latex');

ylabel( ...
    '$F\;(\mathrm{N})$', ...
    'Interpreter', 'latex');

hold off;

%% 8. Theta-r trajectories

figure( ...
    'Name', ...
    'Trajectories relative to equilibrium curve', ...
    'Color', 'w');

hold on;
grid on;
box on;

theta_curve = ...
    linspace(-0.25, 0.25, 600);

r_curve = ...
    equilibrium_factor*tan(theta_curve);

plot( ...
    theta_curve, ...
    r_curve, ...
    '--k', ...
    'LineWidth', 2, ...
    'DisplayName', ...
    '$r_{\mathrm{eq}}(\theta)$');

for j = 1:num_cases
    plot( ...
        results(j).z(:, 1), ...
        results(j).z(:, 3), ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5, ...
        'DisplayName', sprintf( ...
            '$k=%+g$ N/m', ...
            results(j).k));

    plot( ...
        results(j).z(end, 1), ...
        results(j).z(end, 3), ...
        'x', ...
        'Color', case_colors(j, :), ...
        'LineWidth', 1.5, ...
        'MarkerSize', 8, ...
        'HandleVisibility', 'off');
end

plot( ...
    theta0, ...
    r0, ...
    'ko', ...
    'MarkerFaceColor', 'y', ...
    'MarkerSize', 8, ...
    'DisplayName', ...
    'Initial state');

xlabel( ...
    '$\theta\;(\mathrm{rad})$', ...
    'Interpreter', 'latex');

ylabel( ...
    '$r\;(\mathrm{m})$', ...
    'Interpreter', 'latex');

title( ...
    'Motion relative to the instantaneous equilibrium curve', ...
    'Interpreter', 'latex');

legend( ...
    'Location', 'eastoutside', ...
    'Interpreter', 'latex');

hold off;

%% 9. Final summary

fprintf('\nFinal valid states:\n');
fprintf([ ...
    '------------------------------------------------', ...
    '--------------------------------------------\n']);

for j = 1:num_cases
    final_state = results(j).z(end, :);

    fprintf( ...
        ['k = %+7.1f N/m, ', ...
         'c = %+6.1f N*s/m, ', ...
         't = %.6f s, ', ...
         'theta = %+12.6f rad, ', ...
         'r = %+12.6f m, ', ...
         'max|F| = %.6f N'], ...
        results(j).k, ...
        results(j).velocity_gain, ...
        results(j).t(end), ...
        final_state(1), ...
        final_state(3), ...
        max(abs(results(j).F)));

    if results(j).stopped_early
        fprintf('  [stopped early]\n');
    else
        fprintf('  [completed]\n');
    end
end