function dq = model_kinematics(x,p)
% q=[psi theta phi r gamma xG yG].
x=x(:);
s1=x(1);
s2=x(2);
s3=x(3);
sr=x(4);
sg=x(5);
psi=x(6);
theta=x(7);
phi=x(8);
r=x(9);
gamma=x(10);
xG=x(11);
yG=x(12);
g=p.g;
R=p.R;
mw=p.mw;
JW1=p.JW1;
JW2=p.JW2;
mr=p.mr;
JR=p.JR;
BR=p.BR;
h=p.h;
mp=p.mp;
JPx=p.JPx;
JPy=p.JPy;
JPz=p.JPz;
BP=p.BP;
dq=zeros(7,1);
dq(1) = -(-s3/cos(theta));
dq(2) = -(-s1);
dq(3) = -(-s2 + s3*tan(theta));
dq(4) = -(-R*s1 - sr);
dq(5) = -(s3*tan(theta) - sg);
dq(6) = -(-R*s1*sin(psi)*cos(theta) - R*s2*cos(psi));
dq(7) = -(R*s1*cos(psi)*cos(theta) - R*s2*sin(psi));
end
